Documentation/FAQ.md, Documentation/GettingStarted.md
Fixing broken links in FAQ and GettingStarted pages
=> Fix links in FAQ and GettingStarted pages

Classes/CocoaLumberjack.swift
Mainly, changing the context type from `UInt` to `Int`.
=> Update the Swift additions:

Classes/DDFileLogger.m
https://github.com/CocoaLumberjack/CocoaLumberjack/issues/453
=> Fix KVO crash when running unit tests.

Classes/DDFileLogger.m
- Several minor style changes for array access
=> Update older syntax to modern subscripting for array access

Classes/DDASLLogCapture.m
When debug into the exception breakpoint, the message is "xpcproxy[1043] Container: /private/var/mobile/Containers/Data/Application/3FFD12FD-0F9C-43C6-9B0C-38FC1472218B (sandbox)", but the "asl_get(msg, ASL_KEY_TIME_NSEC)" expression is nil.
Crashed Thread:  3 Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSString stringWithUTF8String:]: NULL cString' Last Exception Backtrace:
0   CoreFoundation                      0x251e549f  + 126
1   libobjc.A.dylib                     0x329fcc8b objc_exception_throw + 38
2   CoreFoundation                      0x251e53e5 -[NSException initWithCoder:] + 0
3   Foundation                          0x25e26a0b +[NSString stringWithUTF8String:] + 74
4   demo …
=> fixed crash on DDASLLogCapture when TIME or TIME_NSEC is NULL

Classes/CocoaLumberjack.modulemap, CocoaLumberjack.podspec
Related to #481, here's a first pass at a modulemap for the Lumberjack project, and passing it along with the podspec.
Feedback welcomed.
=> Custom modulemap for podspec

Framework/Mobile/Lumberjack.xcodeproj/project.pbxproj
the project didn't compile. i changed the prefix header path and file name to adapt to its actual name and location.
=> improper prefix header path for mobile app file

Classes/DDLogMacros.h, README.md
Fix #478 by reverting #473
The #ifdef ddLogLevel was a bad idea and it created more issues than solved.
=> Fix #478 by reverting #473 

Classes/CocoaLumberjack.modulemap, Classes/CocoaLumberjack.swift, Classes/DDLegacyMacros.h, Classes/DDLog.h, CocoaLumberjack.podspec, Framework/Lumberjack/CocoaLumberjack.modulemap, Framework/Lumberjack/CocoaLumberjackSwift.h, Framework/Mobile/Lumberjack.xcodeproj/xcshareddata/xcschemes/LibTest.xcscheme, Framework/SwiftTest/AppDelegate.swift, Lumberjack.xcodeproj/project.pbxproj, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/FmwkTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/SwiftTest.xcscheme, Tests/CocoaLumberjack Tests.xcodeproj/xcshareddata/xcschemes/OS X Tests.xcscheme, Tests/CocoaLumberjack Tests.xcodeproj/xcshareddata/xcschemes/iOS Tests.xcscheme
This incorporates the fixes in the `swift_support` branch into the `master` branch, as well as fixes a compile error.
=> Swift 1.2 fixes

Framework/Mobile/Lumberjack.xcodeproj/project.pbxproj
Wasn't included in Xcode project
=> Fix issue in standalone build with DDLegacyMacros.h

Classes/DDTTYLogger.h
=> Add ignore warning mark for "DDMakeColor"

Classes/DDASLLogger.h
=> Typo: minor fix

.travis.yml, Classes/DDFileLogger.h, Classes/DDLog.h, CocoaLumberjack.podspec
Using Xcode 7 image on Travis CI for testing Swift 2.0.
=> Using Xcode 7 image on Travis CI for testing Swift 2.0

Classes/Extensions/DDDispatchQueueLogFormatter.m
The thread safety counter is being incremented by zero...
=> Surely we should be adding 1, not 0?

Classes/DDFileLogger.h, Classes/DDLog.h
=> Remove unnecessary NS_DESIGNATED_INITIALIZERs

Documentation/GettingStarted.md
Updated documentation to reflect required setup instructions for 2.0.1.
See issue #542
=> Updated GettingStarted.md to include `ddLogLevel`

Classes/DDLog.m, Classes/Extensions/DDMultiFormatter.m, Framework/Lumberjack/CocoaLumberjackSwift.h, Lumberjack.xcodeproj/project.pbxproj, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-tvOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-tvOS.xcscheme
Replaying #605 in a separate branch.
=> Support tvOS

Classes/DDLog.h
I found that one NS_DESIGNATED_INITIALIZER removed, so re-added it.
=> Re-add NS_DESIGNATED_INITIALIZER

Classes/DDTTYLogger.h, Classes/DDTTYLogger.m
This PR replaces #497 which has conflicts. The author of the commit is still @weissi.
Fixes #488
=> Fix Issue #488: Support DDLog without AppKit Dependency (#define DD_CLI)

Lumberjack.xcodeproj/project.pbxproj, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-tvOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-tvOS.xcscheme
tvOS targets are removed when merge master into this branch, So I re-add missing tvOS targets.
=> Re-Add missing tvOS targets

Classes/DDLog.m, Classes/Extensions/DDMultiFormatter.m, Lumberjack.xcodeproj/project.pbxproj
I found some problems on merge, So I revert some codes from that.
=> Revert some codes

.travis.yml, Framework/Lumberjack/CocoaLumberjackSwift.h, Framework/tvOSSwiftTest/AppDelegate.swift, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Back.imagestacklayer/Content.imageset/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Back.imagestacklayer/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Front.imagestacklayer/Content.imageset/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Front.imagestacklayer/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Middle.imagestacklayer/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Small.imagestack/Back.imagestacklayer/Content.imageset/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Small.imagestack/Back.imagestacklayer/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Small.imagestack/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Small.imagestack/Front.imagestacklayer/Content.imageset/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Small.imagestack/Front.imagestacklayer/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Small.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Small.imagestack/Middle.imagestacklayer/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/Contents.json, Framework/tvOSSwiftTest/Assets.xcassets/LaunchImage.launchimage/Contents.json, Framework/tvOSSwiftTest/Base.lproj/Main.storyboard, Framework/tvOSSwiftTest/Formatter.swift, Framework/tvOSSwiftTest/Info.plist, Framework/tvOSSwiftTest/ViewController.swift, Lumberjack.xcodeproj/project.pbxproj, Lumberjack.xcodeproj/xcshareddata/xcschemes/tvOSSwiftTest.xcscheme
I add tvOSSwiftTest demo for testing on simulator, and add some tests on Travis CI.
=> Add tvOSSwiftTest demo, Add some tests on Travis CI

Documentation/CustomFormatters.md
This would have been useful to me when reading this tutorial, so I thought i'd propose adding it!
Thanks!
=> Add line showing how to add a custom formatter to a logger

Classes/Extensions/DDContextFilterLogFormatter.m, Classes/Extensions/DDDispatchQueueLogFormatter.m
=> OSSpinLock

Lumberjack.xcodeproj/project.pbxproj, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS-Static.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-watchOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-iOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-watchOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/FmwkTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/SwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/iOSLibStaticTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/iOSSwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/watchOSSwiftTest.xcscheme
These changes are a result of clicking the warning to 'update to recommended settings' and unchecking all suggestions. Someone else with more knowledge of the project may want to accept some of the changes it suggests. I just did this to lose the warning.
=> Updated schemes to latest Xcode

Classes/DDLog.h
Just a small typo fix(but this fix will be helpful for intellisense).
I noticed this when I responded to #663.
=> A small typo fix

Documentation/GettingStarted.md
improve strict declaration at `GettingStarted.md`
=> improve strict declaration

Classes/CocoaLumberjack.swift
=> Update to Swift 2.2: Change `__FUNCTION__` to `#function`, `__FILE__` to `#file`

Lumberjack.xcodeproj/project.pbxproj
This will add support for tvOS.
=> Add appletvos and appletvsimulator and TVOS_DEPLOYMENT_TARGET

Demos/WebServerIPhone/Classes/WebServerIPhoneAppDelegate.m
This fixes the crash in the Demo for WebServerIphone, setting the rootViewController.
...
=> Fixed crash adding the rootViewController

Classes/CocoaLumberjack.swift, Classes/DDASLLogCapture.h, Classes/DDASLLogger.h, Classes/DDLog.h, Classes/DDTTYLogger.h, Framework/SwiftTest/AppDelegate.swift, Framework/iOSSwift/AppDelegate.swift, Framework/tvOSSwiftTest/AppDelegate.swift, Framework/watchOSSwiftTest Extension/ExtensionDelegate.swift
This merge request fixes / reffers to the following issues: none
This changes some class functions into class properties, making the functions be seen by Swift as properties.
=> Add class properties.

README.md
* [Y] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [Y] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [Y] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none
* [Y] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [n/a] I have added the required tests to prove the fix/feature I am adding
* [Y] I have updated the documentation (if necesarry)
* [Y] I have run the tests and they pass
* [Y] I have run the lint and it passes (`pod lib lint`)
Incorrect Swift usage …
=> Update swift usage instructions

Classes/DDLog.h
This merge request fixes / reffers to the following issues: 
Adds nullability metadata to DDLog.h
This adds nullability metadata to DDLog.h, making it easier to use with Swift code.
=> Nullability

.travis.yml, Tests/CocoaLumberjack Tests.xcodeproj/project.pbxproj
* [N/A] I have added the required tests to prove the fix/feature I am adding
--> I modified travis.yml to solve issue.
This merge request fixes / reffers to the following issues: #806 
This Pull Request fix the issue 'Travis-CI test always fails.
See #806 .
This PR summary is here. 
* added settings for CodeCov with Objective-C
* changed settings of `CocoaLumberjack Tests project` to work with travis ci test
* added settings for tvOS with travis ci test
For details, check each commits.
Thanks.
=> Fix Travis-CI Test

README.md
* [N/A] I have added the required tests to prove the fix/feature I am adding
I added a kindly explanation about using CocoaPods with Swift.
The Podfile is the example when developer uses CocoaPods 1.x.x and Swift 3.0.
=> Add a kindly explanation about using CocoaPods

Classes/DDLog.h
=> Fix nullability annotation to match docs

README.md
...
Change Swift example code to use the `CocoaLumberjackSwift` module instead of `CocoaLumberjack` so that the convenience functions `DDLogWarn`, `DDLogError` etc work.
=> Updated README.md Swift example

Framework/Lumberjack/CocoaLumberjack.h
Reverts CocoaLumberjack/CocoaLumberjack#796
=> Revert "Conditionally include CLIColor in umbrella header"

.travis.yml, Classes/CLI/CLIColor.h, Classes/CLI/CLIColor.m, Classes/CocoaLumberjack.h, Classes/DDTTYLogger.h, CocoaLumberjack.podspec, Documentation/GettingStarted.md, Framework/Lumberjack/CocoaLumberjack.h, Lumberjack.xcodeproj/project.pbxproj, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-macOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-macOS.xcscheme
This merge request fixes the following issues: #790 
This merge request refers to the following issues: #782 
I encountered the similar error that #790 mentions.
As #782 mentions, in the first place,  mixing `universal  and the specific platform target` does not seem to be good.
So I changed the framework form `CocoaLumberjack/CocoaLumberjackSwift(for Universal)` to `CocoaLumberjack-macOS/CocoaLumberjackSwift-macOS(for macOS)`.
(For additional info, these target are actually used only for macOS as long as I check `.travis.yml` and `GettingStarted.md`.)
**And I fixed trivial bug(see https://github.com/CocoaLumberjack/CocoaLumberjack/commit/2bd6b6f86c15983d1695049993236bb8bc03e5a2).**
This PR should fix the issue #790. At least I confirmed that Carthage build has been successful about every …
=> Fix Carthage building failure

Classes/DDASLLogger.m, Classes/DDLog.m
Fixed multiple compilation warnings when compiling with `-Wall -Wextra` options.
=> Fixed multiple compilation warnings when compiling with -Wall -Wextra options.

Classes/DDLog.m
I propose to optimize OS detection in `USE_DISPATCH_CURRENT_QUEUE_LABEL` and `USE_DISPATCH_GET_CURRENT_QUEUE`macros by using `dispatch_once_f()` call on iOS and macOS. I use `dispatch_once_f()` instead of `dispatch_once()` to save more CPU cycles.
I wonder if it could optimize `USE_PTHREAD_THREADID_NP` as well: this would replace one double comparison by two boolean comparisons in the best case scenario.
=> Optimized USE_DISPATCH_CURRENT_QUEUE_LABEL and USE_DISPATCH_GET_CURRENT_QUEUE macros.

Classes/DDLog.h, Classes/DDLog.m
=> Added option to not copy messages.

Classes/DDTTYLogger.m
Instead of creating a new calendar for each log output, store it in the logger queue specifics.
=> Store calendar in logger queue specifics for multi-thread safety.

Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS-Static.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-macOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-tvOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-watchOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-iOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-macOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-tvOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-watchOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/FmwkTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/SwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/iOSLibStaticTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/iOSSwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/tvOSSwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/watchOSSwiftTest.xcscheme
=> Scheme version upgrades

Classes/DDOSLogger.h, Classes/DDOSLogger.m
`DDOSLogger` is actually available from the latest Operating Systems(iOS 10.0, macOS 10.12, tvOS 10.0, or watchOS 3.0).
=> Add API_AVAILABLE macro

.travis.yml, Framework/iOSSwift/Formatter.swift, Framework/tvOSSwiftTest/Formatter.swift, Framework/watchOSSwiftTest Extension/Formatter.swift, Lumberjack.xcodeproj/project.pbxproj
I updated Xcode to 8.3 and fixed warning in sample code to support Swift 3.1.
See [SR-1882](https://bugs.swift.org/browse/SR-1882) for the language change about it.
=> Update Xcode to 8.3

.travis.yml
**This pull request fixes the failure in Travis CI.**
As mentioned on [The Travis CI Blog](https://blog.travis-ci.com/2017-04-05-xcode-82-83-duplicate-simulator-fixes), at last, the issue of `duplicate simulators` has been solved. And then each simulator name seems to be changed.
So I corrected a simulator name for iOS Tests.
=> Fix failure in Travis CI

Classes/DDFileLogger.m
Before it was deleted the new files first when multiple files created in a minute.
- Change new log file name : Added  seconds to file name so it will note duplicate file name even if multiple file create within same minute
- update sortedLogFileInfos method based on file name which have date along with seconds so we can compare even  if multiple files created in a minute
...
=> Fix issue of sorting file for delete file, it will delete oldest file first

.github/PULL_REQUEST_TEMPLATE.md
Fixed a typo in the pull request template.
=> Fixed typo in pull request template.

Classes/DDOSLogger.m
=> Fix #883 static_assert error

Classes/CocoaLumberjack.swift, Lumberjack.xcodeproj/project.pbxproj, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS-Static.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-macOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-tvOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-watchOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-iOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-macOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-tvOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-watchOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/FmwkTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/SwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/iOSLibStaticTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/iOSSwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/tvOSSwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/watchOSSwiftTest.xcscheme
=> Update to Swift 4

Classes/DDFileLogger.m
Fix typo: formater -> formatter
=> Fix typo: formater -> formatter.

Lumberjack.xcodeproj/project.pbxproj
* [-] I have added the required tests to prove the fix/feature I am adding
* [-] I have updated the documentation (if necesarry)
This links the CocoaLumberjack (core) framework into the various CocoaLumberjackSwift. For iOS, this was done in aff40b458d5b47ebf3e583d8662b75a009f9b38a. I've now done the same for macOS, tvOS and watchOS...
=> Link CocoaLumberjack into CocoaLumberjackSwift frameworks

Lumberjack.xcodeproj/project.pbxproj
This merge request fixes the following issues: #901
Adds `DDOSLogger.m` to each target correctly.
=> Fix linking error about DDOSLogger

Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS-Static.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-macOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-tvOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-watchOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-iOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-macOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-tvOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-watchOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/FmwkTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/SwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/iOSLibStaticTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/iOSSwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/tvOSSwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/watchOSSwiftTest.xcscheme
Just a version bump to get rid of the warning
=> upgrade schemes

.travis.yml
The public image of Xcode 9.3 has been released. 
https://github.com/travis-ci/travis-ci/issues/9416 
This is a pull request to upgrade it.
=> Replace 9.3beta with 9.3 about Xcode image file

Classes/DDAssertMacros.h
This fixes a small typo in a doc comment.
=> Fix typo in doc comment

Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS-Static.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-macOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-tvOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-watchOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-iOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-macOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-tvOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-watchOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/FmwkTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/SwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/iOSLibStaticTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/iOSSwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/tvOSSwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/watchOSSwiftTest.xcscheme
=> Xcode version bumps

.travis.yml
This merge request is related to #938 .
Uses Xcode 9.4 image for tests.
=> Uses Xcode 9.4 image for tests.

Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS-Static.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-macOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-tvOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-watchOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-iOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-macOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-tvOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-watchOS.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/FmwkTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/SwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/iOSLibStaticTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/iOSSwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/tvOSSwiftTest.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/watchOSSwiftTest.xcscheme
=> Xcode 10 scheme changes

.github/stale.yml
Add configuration file for stale bot.
=> Add Stale Bot configuration

Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests.xcodeproj/xcshareddata/xcschemes/OS X Tests.xcscheme, Tests/Tests.xcodeproj/xcshareddata/xcschemes/iOS Tests.xcscheme, Tests/Tests/DDAtomicCounterTests.m, Tests/Tests/DDBasicLoggingTests.m, Tests/Tests/DDLogMessageTests.m, Tests/Tests/DDLogTests.m, Tests/Tests/DDSMocking.h, Tests/Tests/DDSMocking.m
This merge request fixes / refers to the following issues: #970 
This does some smaller cleanup after #970.
- Mostly code style.
- Some settings were set in the build settings instead of being derived from the xcconfigs.
- Re-added some scheme settings (coverage gathering)
- Enabled some new scheme settings (target-based coverage gathering, parallel testing and random test order).
=> Cleanup after #970

README.md
It looked like this is a iOS 12+ only project.
=> Reflect iOS 8+ support

Classes/CocoaLumberjack.h, Classes/DDASLLogger.m, Classes/DDFileLogger.m, Classes/DDLog.h, Classes/DDLoggerNames.h, Classes/DDLoggerNames.m, Classes/DDOSLogger.m, Classes/DDTTYLogger.m, Lumberjack.xcodeproj/project.pbxproj, Tests/Tests/DDOSLoggingTests.m
Loggers names enum has been added.
=> Logger names have been added.

CHANGELOG.md, Classes/DDFileLogger.m, Classes/DDLog.m
This merge request fixes / refers to the following issues: #878 
This fixes some thread safety issues. See referenced issues above.
=> Fix thread safety issue in DDFileLogger

Tests/Tests/DDBasicLoggingTests.m
=> tests: tests for multiple loggers have been added.

README.md
This merge request fixes / refers to the following issues: None
Update Documentation links in README for pointing to the formatted ones.
=> Update Documentation links

CHANGELOG.md
This release is getting rather large, so I thought I'd sort the contributions by relevance to the reader. I haven't removed any contributions entirely, but I have merged a few very similar lines.
=> Organize CHANGELOG.md.

.travis.yml, Benchmarking/Benchmarking.xcodeproj/project.pbxproj, Benchmarking/Benchmarking.xcodeproj/xcshareddata/IDETemplateMacros.plist, Benchmarking/Benchmarking.xcodeproj/xcshareddata/xcschemes/Benchmarking.xcscheme, Benchmarking/main.m, Classes/DDFileLogger+Internal.h, Classes/DDFileLogger.h, Classes/DDFileLogger.m, Classes/Extensions/DDFileLogger+Buffering.m, Configs/Module-Shared.xcconfig, Tests/Library/DDSampleFileManager.h, Tests/Library/DDSampleFileManager.m, Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests.xcodeproj/xcshareddata/xcbaselines/432B533F1AAE425D00843E69.xcbaseline/AB613018-19D0-4E38-845A-D0F077AAF499.plist, Tests/Tests.xcodeproj/xcshareddata/xcbaselines/432B533F1AAE425D00843E69.xcbaseline/Info.plist, Tests/Tests.xcodeproj/xcshareddata/xcschemes/OS X Tests.xcscheme, Tests/Tests.xcodeproj/xcshareddata/xcschemes/iOS Tests.xcscheme, Tests/Tests/DDAtomicCounterTests.m, Tests/Tests/DDBasicLoggingTests.m, Tests/Tests/DDFileLoggerPerformanceTests.m, Tests/Tests/DDFileLoggerTests.m, Tests/Tests/DDLogFileManagerTests.m, Tests/Tests/DDSMocking.m
Fix buffering code being bypassed.
Optimize buffering implementation.
Provide flush implementation which works as expected on buffered file logger.
Avoid extra queue dispatches and checks.
=> Flushing buffered logger, and ensure buffer is buffering

CHANGELOG.md, Demos/CustomLogLevels/CustomLogLevelsAppDelegate.m, Documentation/CustomLogLevels.md
This merge request fixes to the following issues: #757 #759 
Demo and document about CustomLogLevels is old. These are for legacy version(CocoaLumberjack `1.9.x or before`).
Then I have updated them for recent versions.
=> Update demo and document about CustomLogLevels

.github/ISSUE_TEMPLATE.md
=> Mention `bt all` in isssue template.

Classes/DDLog.m
Some checks for `sync` parts have been added.
=> DDLog checks for NULL values and for global queue dispatching has been added.

Classes/DDOSLogger.h, Classes/DDOSLogger.m
- OS Logger subsystem and category support has been added.
=> core: loggers os logger variations have been added.

CHANGELOG.md, CocoaLumberjack.podspec, Framework/Lumberjack/CocoaLumberjack-Info.plist, Framework/Lumberjack/CocoaLumberjackSwift-Info.plist
I'm in favor of releasing CocoaLumberjack `3.5.2`.
So I bumped version. Could you review this?
=> Bump version to 3.5.2

.travis.yml, CHANGELOG.md, CocoaLumberjack.podspec, Configs/Module-Shared.xcconfig, Integration/Integration.xcodeproj/xcshareddata/xcschemes/iOSFrameworkIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/iOSStaticLibraryIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/iOSSwiftIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/macOSSwiftIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/tvOSSwiftIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/watchOSSwiftIntegration (Notification).xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/watchOSSwiftIntegration.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-Static.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift.xcscheme, README.md, Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests.xcodeproj/xcshareddata/xcschemes/OS X Tests.xcscheme, Tests/Tests.xcodeproj/xcshareddata/xcschemes/iOS Tests.xcscheme
Set Xcode 10.2 and Swift 5.0 as a default.
=> Set Xcode 10.2 and Swift 5.0 as a default

CocoaLumberjack.podspec, Framework/Lumberjack/CocoaLumberjack-Info.plist, Framework/Lumberjack/CocoaLumberjackSwift-Info.plist
Publish the version 3.5.3 to be able to use swift 5
...
=> Prepare version 3.5.3

CHANGELOG.md
This merge request fixes / refers to the following issues: #1069
=> Wrap up CHANGELOG for releasing 3.5.3

.github/stale.yml
This adds "Good First Issue" to the list of ignored labels for StaleBot.
=> Add "Good First Issue" to list of ignored labels

Dangerfile
Updates the `Dangerfile` to match recent changes in the repository structure.
The following updates were made:
- Update paths that still used the old "Classes" folder with the new "Sources" folder.
- Exclude the Package.swift files from the copyright checks.
- Exclude the CocoaLumberjackSwiftSupport include headers from the file structure check.
=> Update Dangerfile to match recent changes to the file structure #trivial

.travis.yml, CHANGELOG.md, CocoaLumberjack.podspec, Configs/Module-Shared.xcconfig, Integration/Integration.xcodeproj/project.pbxproj, Integration/Integration.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Integration/Integration.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Integration/Integration.xcodeproj/xcshareddata/xcschemes/iOSFrameworkIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/iOSStaticLibraryIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/iOSSwiftIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/macOSSwiftIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/tvOSSwiftIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/watchOSSwiftIntegration (Notification).xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/watchOSSwiftIntegration.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-Static.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift.xcscheme, Package@swift-5.0.swift, Sources/CocoaLumberjack/Supporting Files/CocoaLumberjack-Info.plist, Sources/CocoaLumberjackSwift/Supporting Files/CocoaLumberjackSwift-Info.plist, Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Tests/Tests.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Tests/Tests.xcodeproj/xcshareddata/xcschemes/OS X Tests.xcscheme, Tests/Tests.xcodeproj/xcshareddata/xcschemes/iOS Tests.xcscheme
This updates the projects to Xcode 11 and adds some missing changelog entries.
It further prepares the release of a version 3.6.0
=> Prepare release 3.6.0

README.md
This merge request fixes / refers to the following issues: #1090 
I have updated README about Swift usage in detail.
=> Update README about Swift usage.

README.md
* [-] I have added the required tests to prove the fix/feature I am adding
* [-] I have run the tests and they pass
* [-] I have run the lint and it passes (`pod lib lint`)
This merge request fixes / refers to the following issues: #1090, and typos found in #1108
While fixing the typo found in #1108 by @mackuba, I've decided to slightly re-structure the README and add sections for each integration method. Previously, it seemed like CocoaPods is the only integration methods. Only further down we mentioned Carthage and manual installation as well. Swift Package Manager was missing completely.
So I decided to give each integration method a separate section.
=> Restructure README #trivial

CHANGELOG.md, Sources/CocoaLumberjack/DDFileLogger.m, Tests/CocoaLumberjackTests/DDFileLoggerTests.m, Tests/CocoaLumberjackTests/DDSampleFileManager.h, Tests/CocoaLumberjackTests/DDSampleFileManager.m
This merge request fixes / refers to the following issues: #1078 
Slightly better fix than #1084
=> Fixed -didArchiveLogFile: invocation.

CHANGELOG.md, Sources/CocoaLumberjack/DDLog.m, Sources/CocoaLumberjack/Extensions/DDDispatchQueueLogFormatter.m, Sources/CocoaLumberjack/include/DDDispatchQueueLogFormatter.h, Sources/CocoaLumberjack/include/DDLog.h, Tests/CocoaLumberjackTests/DDLogMessageTests.m
IMHO this is a good addition that helps a lot when debugging threads stuff.
What do you think about it?
=> Added support for thread QOS in DDLogMessage class.

CHANGELOG.md, CocoaLumberjack.podspec, Configs/Module-Shared.xcconfig
This merge request fixes / refers to the following issues: -
Prepare a new release v3.6.1
=> Version 3.6.1 #trivial

Sources/CocoaLumberjack/DDASLLogCapture.m, Sources/CocoaLumberjack/DDASLLogger.m
=> Fixed deprecation warnings.

CHANGELOG.md, Sources/CocoaLumberjack/include/CocoaLumberjack/DDDispatchQueueLogFormatter.h, Sources/CocoaLumberjack/include/CocoaLumberjack/DDLoggerNames.h, Tests/CocoaLumberjackSwiftTests/DDLogCombineTests.swift
=> Added swift qos names

.github/workflows/validations.yml
This should finally finalize the GitHub Actions definition for our validations.
There were still some failures, but I've now created a test repository (https://github.com/ffried/ActionsTest/pull/1) and tested my changes so that I (hopefully) don't have to use the CocoaLumberjack repository for the trial-error approach.
=> Finalize validations GitHub actions

CHANGELOG.md, Sources/CocoaLumberjackSwift/CocoaLumberjack.swift
Update Swift log "Any" support, related issue: #1144
=> Update Swift log any support

CHANGELOG.md, CocoaLumberjack.podspec, Configs/Module-Shared.xcconfig
=> Prepare release 3.6.2 #trivial

CHANGELOG.md
Merged #1153 a tad early. This fixes the changelog position of the corresponding entry.
=> Move changelog entry to the right section #trivial

Documentation/DynamicLogLevels.md
=> Remove typo #trivial

Sources/CocoaLumberjack/DDTTYLogger.m
This merge request fixes / refers to the following issues: -
This simplifies some checks in `DDTTYLogger`, making a "fake" stack allocation of 1 unnecessary.
=> Improve TTYLogger checks #trivial

Sources/CocoaLumberjack/include/CocoaLumberjack/DDLog.h
=> Fix spelling error

Sources/CocoaLumberjack/DDLog.m
=> Fix semaphore deadlook

Lumberjack.xcodeproj/project.pbxproj, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-Static.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift.xcscheme
Xcode project and scheme version bumps
=> Scheme and project updates for Xcode 12.3

CHANGELOG.md, Sources/CocoaLumberjack/DDFileLogger.m
This merge request fixes / refers to the following issues: #1203 
Prevent logging an error if the file was already deleted.
=> Prevent error message when file was deleted

CHANGELOG.md, Documentation/CocoaLumberjack.mdj, Lumberjack.xcodeproj/project.pbxproj, Sources/CocoaLumberjack/Extensions/DDContextFilterLogFormatter+Deprecated.m, Sources/CocoaLumberjack/Extensions/DDContextFilterLogFormatter.m, Sources/CocoaLumberjack/Supporting Files/CocoaLumberjack.h, Sources/CocoaLumberjack/include/CocoaLumberjack/DDContextFilterLogFormatter+Deprecated.h, Sources/CocoaLumberjack/include/CocoaLumberjack/DDContextFilterLogFormatter.h, Tests/CocoaLumberjackTests/DDContextFilterLogFormatter+DeprecatedTests.m, Tests/CocoaLumberjackTests/DDContextFilterLogFormatterTests.m, Tests/Tests.xcodeproj/project.pbxproj
This merge request fixes / refers to the following issues: #1214
Use inclusive words(Change `blacklist/whitelist` to `denylist/allowlist`).
=> Use inclusive words - denylist / allowlist

Documentation/CustomLoggers.md
Fixes formatting in the Custom Loggers doc.
=> fix formatting in the Custom Loggers doc

Sources/CocoaLumberjack/DDFileLogger.m
Reverted PR #1234 since it is was superseded by PR #1240.
=> Reverted PR #1234.

.github/dependabot.yml, .github/workflows/demo-builds.yml, .github/workflows/integration-tests.yml, .github/workflows/library-builds.yml, .github/workflows/unit-tests.yml, .github/workflows/validations.yml, Configs/Module-Debug.xcconfig, Configs/Module-Shared.xcconfig, Integration/Integration.xcodeproj/project.pbxproj, Integration/Integration.xcodeproj/xcshareddata/xcschemes/iOSFrameworkIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/iOSStaticLibraryIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/iOSSwiftIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/macOSSwiftIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/tvOSSwiftIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/watchOSSwiftIntegration (Notification).xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/watchOSSwiftIntegration.xcscheme, Lumberjack.xcodeproj/project.pbxproj, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-Static.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift.xcscheme, Scripts/ci-select-xcode.sh, Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests.xcodeproj/xcshareddata/xcschemes/OS X Tests.xcscheme, Tests/Tests.xcodeproj/xcshareddata/xcschemes/Swift Tests.xcscheme, Tests/Tests.xcodeproj/xcshareddata/xcschemes/iOS Tests.xcscheme
This updates the GitHub actions workflows to use the latest versions of some actions. Also, selecting Xcode now happens via a separate action instead of hard-coding the path inside a script file.
The Dependabot config file was also adjusted to not directly assign issues to me and run whenever GitHub seems fit (no time defined) (-> the original file was copied from one of our repos, that's why there were these settings in there)
=> Repo cleanup #trivial

Lumberjack.xcodeproj/project.pbxproj, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-Static.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift.xcscheme
Bump LastUpgradeCheck/LastUpgradeVersion to 1320.
=> chore: Bump Xcode last upgraded version to 13.2

README.md
This merge request fixes / refers to the following issues: none.
It took me a while to figure out how to use the `DDLogHandler` as backend for swift-log, and I hope this snippet will save you some time.
also I hope I've made it clear enough.
=> ADD: update readme about swift-log usage

Sources/CocoaLumberjack/DDLog.m
=> Avoid using NSString format

Sources/CocoaLumberjack/DDASLLogCapture.m, Sources/CocoaLumberjack/DDTTYLogger.m
Optimized DDTTYLogger timestamps formatting.
=> DDTTYLogger optimisations.

Sources/CocoaLumberjack/DDFileLogger.m
Added comment to explain PR #1287
=> Added comment to PR #1287.

README.md
This merge request fixes / refers to the following issues: Closes #1304
Adds Bugfender to the extensions list in README.
=> Add Bugfender logger

Integration/Integration.xcodeproj/project.pbxproj, Integration/Integration.xcodeproj/xcshareddata/xcschemes/iOSFrameworkIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/iOSStaticLibraryIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/iOSSwiftIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/macOSSwiftIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/tvOSSwiftIntegration.xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/watchOSSwiftIntegration (Notification).xcscheme, Integration/Integration.xcodeproj/xcshareddata/xcschemes/watchOSSwiftIntegration.xcscheme, Lumberjack.xcodeproj/project.pbxproj, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-Static.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack.xcscheme, Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift.xcscheme, Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests.xcodeproj/xcshareddata/xcschemes/OS X Tests.xcscheme, Tests/Tests.xcodeproj/xcshareddata/xcschemes/Swift Tests.xcscheme, Tests/Tests.xcodeproj/xcshareddata/xcschemes/iOS Tests.xcscheme
Updated project files for Xcode 13.4.
=> Updated to Xcode 13.4.

README.md
Related to the change "Update to Xcode 14 / Swift 5.7" #1316
<br/>
Update the backwards compatibility list in README.md.
...
=> Update the backwards compatibility list in README

README.md
<br/>
Hey,
I run a free remote logging service and I've created bindings for CocoaLumberjack. Wondering if it would be ok to link to it in the extensions section?
Thanks!
=> Add Birch to extensions

Sources/CocoaLumberjack/DDFileLogger.m
<br/>
This is a follow up patch I'm using for some time in Monal:
When using multiple processes logging to the same file (for example a Notification Service Extension, a Share Extension etc.), loglines sometimes are interleaved: the logline of one process is interrupted in the middle by the logline of another process, especially for long loglines.
We are using a "binary" log format in Monal (length prefixed json) which makes this problem more visible than with normal text logs (but this problem is present when using normal text logs, too).
@ffried If anything is missing here, just let me know! :)
=> Use flock in file logger to coordinate writes with other processes

Sources/CocoaLumberjack/DDAbstractDatabaseLogger.m, Sources/CocoaLumberjack/DDFileLogger.m, Sources/CocoaLumberjack/DDLog.m, Sources/CocoaLumberjack/DDTTYLogger.m, Sources/CocoaLumberjack/Extensions/DDFileLogger+Buffering.m, Sources/CocoaLumberjack/include/CocoaLumberjack/DDLog.h
<br/>
This merge request fixes / refers to the following issues: none
Reduce code duplication by add convenience assert macros.
=> Improve asserts

Lumberjack.xcodeproj/project.pbxproj, Package.swift, Package@swift-5.5.swift, Package@swift-5.6.swift, Package@swift-5.7.swift, Scripts/generate-podspec.sh, Sources/CocoaLumberjack/PrivacyInfo.xcprivacy
<br/>
This merge request fixes / refers to the following issues: #1397 
Adds a privacy manifest for the `CocoaLumberjack` target.
Open questions / points:
=> Add privacy manifest

README.md
<br/>
Fix a typo of README to avoid misleading when people copying and pasting the products name to Package.swift
=> Fix typo to avoid misleading
