CocoaLumberjack/CocoaLumberjack

Classes/CocoaLumberjack.swift
Framework/Desktop/Lumberjack.xcodeproj/project.pbxproj
Framework/Desktop/Lumberjack/CocoaLumberjack.modulemap
Framework/Desktop/SwiftTest/InfoPlist.strings
Framework/Desktop/SwiftTest/MainMenu.xib

These improvements help make the Swift additions to CocoaLumberjack behave better, as well as fixing some bugs.

Swift improvements

---

Documentation/GettingStarted.md

Changing from legacy LOG_LEVEL_VERBOSE to Lumberjack 2.x DDLogLevelVerbose naming

Updating naming convention

---

Classes/CocoaLumberjack.swift

Now, if you need to pass a string that does use valists under Swift, either switch to using them in a string constant ( "\(aVal)" ), or creating a string manually that uses it ( String(format: "%@", aVal) ).
Should fix #448.

Have the Swift debug functions not take variable arguments.

---

Classes/DDLog.m

Just in case we get passed a mutable string by accident.

Copy the message string

---

Classes/DDLog.h

More details on OS_OBJECT_USE_OBJC  and CocoaPods
http://guides.cocoapods.org/syntax/podspec.html#deployment_target

Fix #433 CocoaLumberjack 2.0.0-rc does not build with Pods

---

Classes/DDFileLogger.m

If the locale is not specified, then the expected format can be overridden in iOS
by the 'use 24hr clock' setting.
This causes filenames with am/pm format, which then fail the isLogFile
test.
This in turn causes sortedLogFilePaths and friends to return zero
entries.
(this bug also exists in the 1.9 branch)
for more detail, see:
https://developer.apple.com/library/ios/qa/qa1480/_index.html

fix locale for dateFormatter to provide fixed output date format.

---

Classes/DDFileLogger.m

When an app that is capable of running in the background runs on the simulator, the most recent log file is always archived, regardless of file size or age. A new log file is created on each app launch because `NSFileProtectionKey` is not present.
This pull request checks whether there is a value for `NSFileProtectionKey` in the log file's attributes. If there is no file protection value present, it will not force a new log file to be created.

New log file is always created at app launch on simulator

---

Classes/DDLogMacros.h

To avoid 
> Requiring apps to create an arbitrary named variable just to start using CocoaLumberjack is clumsy. 
we can define the global log level to **Verbose** unless it's already defined.

Default ddLogLevel set to DDLogLevelVerbose

---

Framework/Desktop/Lumberjack/CocoaLumberjack.modulemap

Temporary fix for #481.
Note that you will need to declare `ddLogLevel` as a preprocessor macro on the command line.
Hopefully Xcode 6.3 will add support for the `textual header` module syntax.

Temporary fix for modules.

---

Classes/DDTTYLogger.h

Using type safe alias for DDColor instead of #define directive. Similarly instead of using #define to define a function that returns UIColor, using static to make it type safe.

Using type safe DDColor alias instead of #define directive.

---

Classes/CocoaLumberjack.swift

The logFlags for Verbose and Error seems to be transposed. Correcting on master, should probably be on the swift_support branch too

Fix seemingly obvious typo in the toLogLevel function

---

Classes/DDLog+LOGV.h

It looks like they were copied from the legacy macros, and only changed in the content of the macro, and not the definition.

Fixed the LogV macros so that avalist is no longer undefined.

---

Classes/DDLog.m

See the original issue https://github.com/CocoaLumberjack/CocoaLumberjack/issues/311

Fix NSLog threadid mismatch with iOS 8+/OSX 10.10+

---

Classes/DDASLLogCapture.m

Several tweaks to DDASLLogCapture.
First, -stop was not working, because a bad token value was used to cancel.  Either the notifyToken value should be declared __block, or the token parameter in the block argument should be used (I did the latter).  Currently, the initial value of 0 is just captured by the block, and is using that to cancel, which doesn't work.
Should use asl_free instead of free I believe, and it should go before the cancel return statement else that would be a leak when stopping.
I don't think there is a need to avoid the log when a timestamp is not provided; so I changed to just use the current time in that situation.
Use "self" instead of a hardcoded class name; that can help if subclassing or copying code to a clone class, if needed for some reason (perhaps to add …

Several fixes/tweaks to DDASLLogCapture. 

---

Classes/DDASLLogCapture.m
Classes/DDASLLogger.h
Classes/DDASLLogger.m

When both `DDASLLogCapture` and `DDASLLogger` are active and you have another logger (for instance the file or tty logger),
using a `DDLog(xxx)` statement would result in 2 log entries with the same message in other loggers.
Indeed, the first (expected) entry would be sent to the registered loggers and then the `DDASLLogger` would send it to the ASL facility, after that the `DDASLLogCapture` would pick it up and it would again be sent to the registered loggers (note that in that case `DDASLLogger` would rightfully skip it since it comes from the capture).
So here I've marked messages sent by `DDASLLogger` with a custom key that's used for filtering in `DDASLLogCapture`. Hence preventing the duplicate messages.

Prevent duplicate log entries when both DDASLLogCapture and DDASLLogger are used

---

Documentation/CustomFormatters.md

The code samples use DDLogFlagWarn, which isn't part of the DDLogFlag enum.
Switch to use DDLogFlagWarning (with the ING) instead. 
Also added spaces to keep things lining up pretty.

Change code samples to use DDLogFlagWarning

---

Framework/Desktop/Lumberjack.xcodeproj/project.pbxproj

In some cases when adding CocoaLumberjack as a submodule, Xcode can get confused and attempts to find the modulemap file in the wrong directory (e.g. `Mobile/Lumberjack/CocoaLumberjack.modulemap`, which does not exist). I'm not sure why happens or in exactly which situations, but using an absolute path (via `$PROJECT_DIR`) makes our intention more explicit and avoids this problem.

Use an absolute path to identify the modulemap.

---

Classes/DDLegacyMacros.h
Classes/DDLog.h

When applying the new `use_frameworks!` option in Cocoapods, a bridging header
is automatically generated. This bridging header must import `DDLegacyMacros.h`
directly.
This leads to `CocoaLumberjack 1.9.x legacy macros enabled.` and `macro
redefined` warnings.
Therefore it is not enough to merely check the flag in DDLog.h.

Move DD_LEGACY_MACROS check to DDLegacyMacros.h

---

Classes/CocoaLumberjack.swift

I had to add the 'context' and 'tag' parameters to DDLogXXX
functions to make it compile. It seems that this is a bug in
the Swift compiler with optional arguments and the use
of @autoclosure.

Fixes compilation issues on Swift 1.2

---

Classes/DDLog.m

DDLogMessage constructor describes the behaviour which has not been implemented. I've added the tests and this pull requests implements the behaviour so the test passes.

Fixing DDLogMessage to work according to the documentation

---

Classes/CocoaLumberjack.swift
Lumberjack.xcodeproj/project.pbxproj

When trying to use the CocoaLumberjackSwift target inside the newly released Xcode 7, several compile-time errors occur due to syntactical changes made in Swift 2.0. I ran Xcode's automatic Swift syntax upgrading assistant, and then manually fixed the change to use OptionSetType rather than bit testing on the DDLogFlag type.
(This is the same as #533, but submitted to the correct branch per @rivera-ernesto 's suggestion.)

Fixed compile errors in Xcode 7 with Swift 2.0

---

Lumberjack.xcodeproj/project.pbxproj

I'm using Cocoa Lumberjack in a static framework distributed to other developers. I want to include armv7s in that framework in case developers want to use armv7s in their own Apps. However, the standard architectures in Xcode 6 and up don't include armv7s, and so the Cocoa Lumberjack targets don't compile for it.
For the dynamic framework the extra architecture consumes more space in the App bundle (750 KB vs 533 KB without), but for the static library I don't think there is any argument against including it as it will be stripped from the final App if not needed.
In this pull request I've just added armv7s to the static library target.

Add armv7s to static library

---

Tests/CocoaLumberjack Tests.xcodeproj/project.pbxproj
Tests/Tests/DDLogMessageTests.m

Hi from Cocoapods TestJam,
I'm trying to add some test coverage for the project. Started with the DDLogMessage as it was simple enough.
There are 2 failing tests because I've wrote tests according to the documentation which mentions using DDLogMessageOptions to force copy the file & function strings but the code is actually missing in the implementation.

Tests for DDLogmessage

---

Classes/CocoaLumberjack.modulemap
Classes/CocoaLumberjack.swift
Classes/DDFileLogger.m
Classes/DDLegacyMacros.h
Classes/DDLog.h
Classes/DDLogMacros.h
Classes/DDTTYLogger.m
CocoaLumberjack.podspec
Framework/Lumberjack/CocoaLumberjack.modulemap
Framework/Lumberjack/CocoaLumberjackSwift.h
Framework/Mobile/Lumberjack.xcodeproj/xcshareddata/xcschemes/LibTest.xcscheme
Framework/SwiftTest/AppDelegate.swift
Lumberjack.xcodeproj/project.pbxproj
Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS.xcscheme
Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack.xcscheme
Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift.xcscheme
Lumberjack.xcodeproj/xcshareddata/xcschemes/FmwkTest.xcscheme
Lumberjack.xcodeproj/xcshareddata/xcschemes/SwiftTest.xcscheme
README.md
Tests/CocoaLumberjack Tests.xcodeproj/project.pbxproj
Tests/CocoaLumberjack Tests.xcodeproj/xcshareddata/xcschemes/OS X Tests.xcscheme
Tests/CocoaLumberjack Tests.xcodeproj/xcshareddata/xcschemes/iOS Tests.xcscheme
Tests/Tests/DDLogMessageTests.m
Tests/Tests/DDLogTests.m

The following are fixes/enhancements to CocoaLumberjack for Swift 2.0/Xcode 7.
Notably, *DDLogMacros.h* can be set as a textual header, making defining custom macros for CocoaLumberjack, such as `ddLogLevel`, less troublesome.

Swift 2 fixes

---

Classes/CocoaLumberjack.swift

* Error when using current head of swift_2.0 branch
* "Cannot import module that is being compiled" ... which actually makes sense compared to most swift xcode errors
* Simply remove the import line

Fix Xcode 7 beta3 "Cannot import module that is being compiled" error

---

Classes/DDTTYLogger.h

This PR adds to the recently merged #553 to include OS X as well as iOS.  It silences an unnecessary warning for those who build with additional warnings enabled.

Extend ignore unused warning pragma to cover all platforms

---

Classes/DDLog.h

Referencing issue #558, this PR changes one import when manually importing CocoaLumberjack files into your Xcode project. The fix was suggested by @robotive.
For those that use them, it would be important to confirm it doesn't spoil integration with CocoaPods and Swift.  (I don't use either yet, so am not confident to verify this).

Fix import for when CL framework files are manually imported into project

---

Classes/DDLog.m
Classes/Extensions/DDDispatchQueueLogFormatter.m

Turning on strict warnings causes complaints about unused parameters.  Flag those parameters as unused to eliminate those warnings.

Flag unused parameters as being unused to silence strict warnings

---

Lumberjack.xcodeproj/project.pbxproj

Currently, CocoaLumberjackSwift-iOS depends on CocoaLumberjack which is Mac target. So I change it to depends on CocoaLumberjack-iOS

Make CocoaLumberjackSwift-iOS target depends on CocoaLumberjack-iOS

---

.travis.yml

This will help to test Swift 1.2 codes.

Using Xcode 6.4 image on Travis-CI for Swift 1.2 environment

---

Classes/DDLog.m
CocoaLumberjack.podspec
Lumberjack.xcodeproj/project.pbxproj

How about this commits for start to support watchOS and resolve #535 issue?
I create pull request on swift_2.0 branch, because it requires Xcode 7 and related to Swift 2.0.
I added watchOS support on CocoaLumberjack target, not on CocoaLumberjack-iOS.
Might be good to integrate CocoaLumberjack-iOS to CocoaLumberjack which mentioned on #383.

Support watchOS

---

Framework/Mobile/Lumberjack.xcodeproj/project.pbxproj

Causes issues with requiring it in the parent app's build settings
Test for LibTest is still missing files for the Mobile project - this is just to prevent the error

Removed images.xcassets from Mobile project

---

Classes/DDASLLogCapture.m
Classes/DDLog.m
Classes/Extensions/DDMultiFormatter.m
Framework/watchOSSwiftTest Extension/Assets.xcassets/README__ignoredByTemplate__
Framework/watchOSSwiftTest Extension/ExtensionDelegate.swift
Framework/watchOSSwiftTest Extension/Formatter.swift
Framework/watchOSSwiftTest Extension/Info.plist
Framework/watchOSSwiftTest Extension/InterfaceController.swift
Framework/watchOSSwiftTest/Assets.xcassets/AppIcon.appiconset/Contents.json
Framework/watchOSSwiftTest/Base.lproj/Interface.storyboard
Framework/watchOSSwiftTest/Info.plist
Lumberjack.xcodeproj/project.pbxproj
Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-watchOS.xcscheme
Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-watchOS.xcscheme
Lumberjack.xcodeproj/xcshareddata/xcschemes/iOSLibStaticTest.xcscheme
Lumberjack.xcodeproj/xcshareddata/xcschemes/watchOSSwiftTest.xcscheme

I tried to add watchOSSwiftTest for testing on watch. And I realized that watchOS target requires another binary than that iOS's one. So we can't use same target for iOS application and watchOS application.
So, I create CocoaLumberjack-watchOS, CocoaLumberjackSwift-watchOS. After that, There are to many targets just for framework, So I merge mobile, desktop framework as mentioned on #383.
I didn't test watchOSSwiftTest on real device yet, but it works well on Watch Simulator.

Add watchOSSwiftTest and some changes on Lumberjack.xcodeproj

---

Classes/DDLog.h

typo in parameter's variable name fixed

---

Lumberjack.xcodeproj/project.pbxproj

Let Xcode 7 run its Swift upgrade check so it doesn't keep modifying the project.

Silence the Xcode 7 upgrade check.

---

Classes/DDLog.m

tvOS will not support `host_info()` anymore. At the same time it will support `[[NSProcessInfo processInfo] activeProcessorCount]` so this can be used instead.

Make build work on tvOS

---

Classes/DDLog.m
Classes/Extensions/DDMultiFormatter.m
Framework/Lumberjack/CocoaLumberjackSwift.h
Lumberjack.xcodeproj/project.pbxproj
Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-tvOS.xcscheme
Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift-tvOS.xcscheme

This will allow include tvOS frameworks on projects, and let Carthage build tvOS framework.

Add tvOS targets on project

---

Classes/DDTTYLogger.h

Use "inline" qualifier on DDMakeColor to get rid of unused function warnings

Kill unused function warnings from DDTTYLogger.h

---

Classes/DDASLLogger.h
Classes/DDFileLogger.m
Classes/DDLog.h
Classes/DDLog.m
Classes/DDTTYLogger.h
Classes/DDTTYLogger.m
Classes/Extensions/DDDispatchQueueLogFormatter.m
Documentation/CustomFormatters.md
Documentation/GettingStarted.md
Documentation/XcodeTricks.md
Framework/Mobile/Lumberjack.xcodeproj/project.pbxproj
Lumberjack.xcodeproj/project.pbxproj

Conflicts:
- .travis.yml
Resolved by choosing the version from the swift_2.0 branch that requires the
xcode7 build environment.
- Classes/DDFileLogger.h
Resolved by choosing the changes from 58ae948 by sinoru over changes from
b765caf by stephencelis.
See discussion on issue #592
- Lumberjack.xcodeproj/project.pbxproj
Resolved by choosing the version from the swift_2.0 branch and manually
redoing what was done in 9f41918.
Since it was branched off master, there have been three new commits modifying
the project file:
- f1cd4b8 Make CocoaLumberjackSwift-iOS Target depend on CocoaLumberjack-iOS
Similar change was done when re-adding CocoaLumberjackSwift-iOS
target again (after it had been removed) in fa57e49
- 9f41918 Mark CocoaLumberjack dynamic libraries as Require Only App-Extension-Safe …

Merge master back into swift_2.0

---

Tests/Tests/DDBasicLoggingTests.m

This cocoapods version is currently only available as a pre-release (in the release-candidate stadium).
It fixes CocoaPods/CocoaPods#4103 and is needed to successfully lint pods with watchOS support.
There was a comment, in line 55 indicating that the block would be called twice
for every log. Appearantly this isn't the case anymore.
Note: I do not fully understand what is going on there and why the behavior seems to have changed.
I only observed the current behavior to be that the block is called exactly once for every log.
@bpoplauschi please double check this commit

Fix CI failures

---

Classes/DDLog.m

As pointed out in #597 the check whether `processorCount` is available is not necessary anymore since min version for OS X is 10.7 and all other platforms supported it from the start.

Remove redundant check for processorCount availability

---

README.md

For some reason, when not giving a branch, Travis CI currently seems to return
the icon for the build status of the `tvOS_Xcode_7.1` branch.
This shows a "failing" icon on the masters Readme.
I think this is a bug in Travis CI, that can be worked around by adding
a branch=master parameter to the svg url

Explicitly name master branch in Travis icon url

---

Classes/Extensions/DDDispatchQueueLogFormatter.h
Classes/Extensions/DDDispatchQueueLogFormatter.m

Attempt to solve crashes in NSDateFormatter still observed in the wild.
Stop using so-called "hybrid approach" when implementation tries to determine in runtime what NSDateFormatter instance to use: the shared one or retrieved from thread dictionary. Now a library user must decide if thread-safe but more expensive behaviour is desired (default) or simple storing date formatter in ivar is sufficient (suitable for using formatter with a single logger).
A few more minor tweaks:
- make simple customisations (like changing date format) easy by exposing a method to configure used NSDateFormatter instance
- set date formatter's calendar once instead of doing that each time a log message is formatted
- use POSIX locale to have consistent timestamp. For example, currently on devices with Arabian …

Fix NSDateFormatter issues

---

Classes/CocoaLumberjack.swift

This was added in a993d7cbb in a misguided attempt to avoid having to
say `logText()` when passing the parameter to `SwiftLogMacro` (see [1]).
Besides being unnecessary, `@autoclosure(escaping)` actually carries a
performance penalty, it breaks the ability to reference properties and
methods on `self` without an explicit `self.` (in string
interpolations), and it makes the function look, to its callers, as
though it actually evaluates the message outside of the scope of the
function, which would be a really terrifying thing if it actually did
that.
[1]: [GitHub comment](https://github.com/CocoaLumberjack/CocoaLumberjack/pull/492#issuecomment-91104180)

Remove (escaping) from the Swift @autoclosure parameters

---

Documentation/GettingStarted.md

I've had a go at updating the Getting Started documentation - and in particular the Manual Installation instructions.
You'll see that I've moved around some of the later instructions for project integration (now called accessing and configuring CLJ).  I've also preferred the non key-based HTTPS URL schemes for the git clone and submodule examples to avoid the risk of permissions errors when getting the source.
I'd be pleased if the team could review these changes for accuracy and any oversights.  As our friends at Apple might say: Focus Areas are CocoaPods, Carthage and Swift ;)

Updating documentation for manual installation

---

Documentation/DynamicLogLevels.md

"registered dynamic logging" is very helpful for me. But as you know, the document seems to be old. So I have updated it(I thought I'd like to contribute!).
Thank you.

make the method names correspond to the one in source(DDLog.h)

---

Documentation/GettingStarted.md
Lumberjack.xcodeproj/project.pbxproj
Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-iOS-Static.xcscheme

IMHO, the configuration of the static library target is suboptimal and doesn't provide a sane default. 
This PR makes the following changes for the static library target:
- The product name is changed to `CocoaLumberjack` instead of the default which resolves to `CocoaLumberjack-iOS-Static`
- A copy-headers phase is added, which copies all the headers to `$(BUILD_PRODUCTS_DIR)/include/CocoaLumberjack`.
- This was also documented in the `Getting Started`
This simplifies the usage of the library in nested/complex project configurations, since the headers can always be found and correctly imported via the angle brackets, i.e.
`#import <CocoaLumberjack/CocoaLumberjack.h>`
provided that the `Header Search Paths` has the entry `$(BUILD_PRODUCTS_DIR)/include`, which many projects already use.

Simplify usage and integration of the static library target

---

Classes/CocoaLumberjack.swift
Classes/DDLog.h
Classes/DDLog.m
Classes/DDLogMacros.h
Framework/FmwkTest/AppDelegate.m
Framework/SwiftTest/AppDelegate.swift

**TL;DR:** This modification in the implementation of `CocoaLumberjack` allows to create instances of `DDLog` which can manage their own loggers.
In the current implementation, `DDLog` can only be used through class methods.
It means the following configuration is not possible:
- Network `DDLog`
- `DDTTYLogger` (verbose level)
- `DDFileLogger` (info level)
- Default `DDLog`
- `DDTTYLogger` (debug level)
- `DDFileLogger` (error level)
Make `DDLog` usable via instances.
Each `DDLog` instance manages its own list of loggers.
By using the singleton instance, `DDLog` class methods continue to work smoothly.
In `Objective-C`, a new brunch of macros are created to get a `DDLog` instance as parameter:
```Objective-C
#define LOG_MACRO_TO_DDLOG(ddlog, isAsynchronous, lvl, flg, ctx, atag, fnct, …
```

DDLog usable via instances

---

Classes/CocoaLumberjack.swift

Rename SwiftLogMacro to _DDLogMessage instead, because SwiftLogMacro is
a weird name for this. Leave the old name behind but marked as
deprecated for now; it should be removed later. Give _DDLogMessage a
more sane argument ordering as well (and no default arguments; it's not
meant for end users to call).
Stop using string interpolation for the `StaticString`s. The comments
say it avoids an integer overflow warning, but I see no such warning
(and never have).
Rewrite `CurrentFileName()` in pure Swift instead of unnecessarily
bridging to Cocoa.

Clean up CocoaLumberjack.swift a little

---

Classes/DDLog.m

Must have for case when CocoalLumberjack is used as shared framework by many other frameworks (pods) and configured in each of them

Added check to prevent duplicate loggers.

---

Framework/Lumberjack/CocoaLumberjack.h

Replace LUmberjack with Lumberjack. Otherwise DDFileLogger.h is not found on case-sensitive file systems.

Typo in import statement

---

Lumberjack.xcodeproj/project.pbxproj

CocoaLumberjackSwift is not currently compatible with Swift 3. This pins the version of Swift to version 2.3 to allow the current code to be safely compiled using both Xcode 7 and Xcode 8 beta.

Pin CocoaLumberjackSwift to Swift 2.3 to allow compilation on Xcode 8.

---

Lumberjack.xcodeproj/project.pbxproj

This merge request fixes / reffers to the following issues: #744 
This pull requests adds CLIColor.h/m to the OS X target and makes sure the header file is shipped with the Framework so that apps without AppKit (or using ```DD_CLI```) that also disable Clang modules can actually use CocoaLumberjack.

Fix CLIColor.h not found for non-AppKit binaries w/o clang modules

---

Classes/DDLog.h
Classes/DDLog.m
Documentation/PerLoggerLogLevels.md
Tests/Tests/DDLogTests.m

In some case, it can be useful to know which are the `DDLogger` associated to `DDLog`. It is currently possible to get these information thank to `[DDLog allLoggers]` method.
However, it is not possible to know the `DDLogLevel` associated to these loggers. This piece of information is stored in the `DDLoggerNode` which is private.
This pull request allows to retrieve these information. It completes the #136.
- A new class `DDLoggerInformation` which contains a logger and its associated level.
- A new public method `[DDLog allLoggersWithLevel]` which returns an array of `DDLoggerInformation`.
- A new private method `lt_allLoggersWithLevel`.
- A unit test which verify `[DDLog allLoggersWithLevel]` method.
- Documentation ([PerLoggerLogLevels.md](https://github.com/CocoaLumberjack/CocoaLumber …

Retrieve the `DDLogLevel` of each logger associated to DDLog

---

Lumberjack.xcodeproj/project.pbxproj

* n/a I have added the required tests to prove the fix/feature I am adding
* n/a I have updated the documentation (if necesarry)
Specify use of Swift 2.3, fixing compilation for iOS in Xcode 8. I ran into this when trying to use CocoaLumberjack via Carthage.
Alternately, the setting could be specified on the project file itself. I saw an earlier commit that set it per-target and followed their lead.

Pin CocoaLumberjackSwift to Swift 2.3 for other targets too

---

Framework/Lumberjack/CocoaLumberjack.h

...
In #745, CLIColor.h was made public. However, there was not a corresponding addition to CocoaLumberjack.h to make this file publicly available. This should fix that issue.
This results in the following error when attempting to import CocoaLumberjack (when built via Carthage):
```
Umbrella header for module 'CocoaLumberjack' does not include header 'CLIColor.h'
```

Expose CLIColor header publicly in cross-platform framework target

---

CocoaLumberjack.podspec

~~* [x] I have added the required tests to prove the fix/feature I am adding~~
--> **but I tested at local machine to execute 'pod install' with the modified CocoaLumberjack.podspec file.**
This merge request fixes / reffers to the following issues: #778
This Pull Request should fix the issue 'Use of undeclared identifier 'LOG_ASYNC_ENABLED'.
See #778.
From CocoaLumberjack 2.4.0 and 3.0.0, modulemap has been automatically created by CocoaPods. As a result, CocoaLumberjack.h has been imported after DD*.h by the umbrella header file(this file is also created by CocoaPods). This is the root cause of above issue.
So I modified 'Default' subspec to import CocoaLumberjack.h before DD*.h. I think this should be the expected action for 'Default' subspec. 
In addition, this PR is to master branch …

modified 'Default' subspec to import CocoaLumberjack.h before DD*.h.

---

Framework/Lumberjack/CocoaLumberjack.h

* n/a I have added the required tests to prove the fix/feature I am adding
* n/a I have updated the documentation (if necesarry)
This merge request fixes / reffers to the following issues: <none>
I get linker errors if I try to run any of the tests, even on master, so I can't test this :(. The compiled framework with this change does work in my app the same as one without the change, at least.
`CocoaLumberjack.h`, what seems to be the include-everything-public header for CocoaLumberjack, includes `CLIColor.h` for all platforms. But `CLIColor.h` is not added as a public header in the project settings for the iOS/watchOS/tvOS targets, e.g. `CocoaLumberjack-iOS`, and therefore is not included in the umbrella header of the resulting frameworks. Including one of those frameworks in an iOS …

Conditionally include CLIColor in umbrella header

---

Classes/DDASLLogger.m

Skip messages in ASL logger which are filtered out by the formatter

---

Documentation/CustomFormatters.md

This removes extra trailing `\n` symbols in the sample code for custom log formatters. Leaving them there results in double newlines in logs.

Remove extra newlines from example code

---

Classes/CLI/CLIColor.h
Classes/CLI/CLIColor.m
Classes/DDTTYLogger.h
Lumberjack.xcodeproj/project.pbxproj

This merge request reffers to the following issues: #815 
Makes universal frameworks.
CocoaLumberjack and CocoaLumberjackSwift target seems to support all platforms **except watchOS**.
So I made these targets support all platforms **including watchOS**.
[Note]
As long as I checked podspec and DDTTYLogegger.h, CLIColor.h should be used only for macOS through DDTTYLogger.h. 
In order to do it, I used `TARGET_OS_IPHONE` macro that means iOS or tvOS or watchOS.

Make universal framework

---

Documentation/ProblemSolution.md

Found an issue while debugging a Share Extension, and wanted to share this tip to make logs more useful/reliable there. I don't believe a code change is necessary - this is just a straight doc contribution.

Add an entry for logging in iOS Extensions

---

Classes/DDLog.m

Running the static analyzer Under Xcode 8.2 results in **Null is returned from a method that is expected to return a non-null value** in +[DDLog registeredClasses].  This due to a possible nil return.  This PR changes that return to an empty array ( @[] ), silencing the warning.
+[DDLog registeredClasses] is used by +[DDLog registeredClassNames, which expects an array object, rather than nil.

Fix static-analyzer error: +[DDLog registeredClasses] returning nil

---

Classes/DDLog.m

Fix crash for ios 9 and 10 
We need the nil or some other way to know how many arguments to grab. `va_list` has no magic way to know when to stop.
Things like `stringWithFormat:` don't need a nil because it determines the number of arguments based on the number of format specifiers (which is why they need to match or your code goes boom). 
What you could do is make use of the following NSString method:
```
va_start(args, format);
NSString *msg = [[NSString alloc] initWithFormat:format arguments:args];
// do whatever
va_end(args);
```
Please help me to review.

Crash  [DDLog log:level:flag:context:file:function:line:tag:format:]

---

Classes/DDAbstractDatabaseLogger.m
Classes/DDFileLogger.m

The leeway parameter of dispatch_source_set_timer() function is an uint64_t value in nanoseconds. I guess you misuse it by putting a float value in it.

Fixed dispatch_source_set_timer() usage.

---

Classes/DDFileLogger.m

Path parameter for method -[NSFileManager attributesOfItemAtPath:error:] cannot be null. Fixed static analyzer warning.

Fixed misuse of non null parameter.

---

Classes/DDLog.h
Classes/DDLog.m

Problem: if a logger doesn't inherit from DDAbstractLogger and doesn't provide a queue (i.e..-loggerQueue returns nil), DDLog will create a queue for it. However it doesn't know anything about this queue and cannot create an environment in it. For formatters, the problem is the same: they don't know on which logger queue they are being added.
I propose this new API to compensate this problem. Maybe we should mark the old notifiers as obsolete…

Added new hooks when adding loggers and formatters.

---

Classes/DDLog.h
Classes/DDLog.m

By enabling -init method, you can write optimized loops like these since all DDLogMessage ivars are public:
`NSMutableArray* lines = [NSMutableArray arrayWithCapacity:array.count];`
`DDLogMessage* logMessage = [[DDLogMessage alloc] init];`
`for (NSDictionary* dict in array) {`
`    logMessage->_message    = …`
`    logMessage->_flag       = …`
`    logMessage->_context    = …`
`    logMessage->_file       = …`
`    logMessage->_function   = …`
`    logMessage->_line       = …`
`    logMessage->_tag        = …`
`    logMessage->_timestamp  = …`
`    logMessage->_threadID   = …`
`    logMessage->_threadName = …`
`    logMessage->_queueLabel = …`
`    [lines addObject:[self formatLogMessage:logMessage withTimestamp:YES]];`
`});` …

Reenable default -init method for DDLogMessage class.

---

Classes/DDLog.h
Classes/DDLog.m

I fixed the signature of DDExtractFileNameWithoutExtension() function since it can returns null values if filePath parameter is null or if -[NSString initWithBytes:] fails.
I also renamed LOG_MAX_QUEUE_SIZE to DDLOG_MAX_QUEUE_SIZE  and make it optional. It will not break existing code since this macro is private (see Discussion #839).

Fixed nullability of DDExtractFileNameWithoutExtension() function.

---

Classes/DDLog.h

`function` should be `nullable` because `aslMessageReceived` clearly calls it with a `null` function.
...

Correct nullability of function

---

Classes/DDTTYLogger.m

By using POSIX API, we can further optimize timestamp calculation. On my Mac, I ran a test in a loop count of 10000000 that shows the difference:
calendar: 9.024821s
localtime: 7.373581s

Optimized timestamp calculation.

---

Classes/CocoaLumberjack.h
Classes/DDOSLogger.h
Classes/DDOSLogger.m
Framework/Lumberjack/CocoaLumberjack.h
Lumberjack.xcodeproj/project.pbxproj

This merge request fixes / reffers to the following issues: 
https://github.com/CocoaLumberjack/CocoaLumberjack/issues/765
I added a first draft of a logger which uses the new os_log API (https://developer.apple.com/reference/os/logging).
The aim is to be future proof and most of all to be able to log more than 1024chars in the device logs (see: https://github.com/CocoaLumberjack/CocoaLumberjack/issues/765)

added a very basic os_log (unified logging) logger

---

Classes/DDFileLogger.h
Classes/DDFileLogger.m

Improves swift compatibility by allowing the following:
```swift
DDLogFileManagerDefault(logsDirectory: "", defaultFileProtectionLevel: .completeUntilFirstUserAuthentication)
```
Instead of being required to do this:
```swift
DDLogFileManagerDefault(logsDirectory: "", defaultFileProtectionLevel: FileProtectionType.completeUntilFirstUserAuthentication.rawValue)
```
Replaces usage of `NSString*` with `NSFileProtectionType` where appropriate.

use NSFileProtectionType instead of NSString*

---

Classes/DDFileLogger.m

This is an additional fix on top of #868.
`-[DDFileLogger sortedLogFileInfos]` was assuming that all files are using the new date format introduced in 44ec1fafc3acab53513e4c0474ee58ee17b044af.
This was resulting in old log files ending up with a nil date when being parsed by `logFileDateFormatter`, which would result in a bad compare: result.
If the date formatter fails to parse a date then we fall back to the file's creation date.
Fixed typo in variable name (`arryComponant` -> `arrayComponent`).

Fixed new log files being deleted immediately when there are logs with the old date format

---

Documentation/PerLoggerLogLevels.md

Added a Swift example
This merge request fixes / refers to the following issues: none
Just a tiny documentation update. The 'Use Log Level per Logger' page lacked a Swift example. Took me long enough to figure it out that I wanted to share it.
Best regards
Guillaume

update 'Use Log Level per Logger' doc

---

Lumberjack.xcodeproj/project.pbxproj

Steps to reproduce:
* Open Lumberjack.xcodeproj
* Select CocoaLumberjackSwift-iOS scheme
* build
See build fail with missing symbol to DDLog:
This diff fixes it by telling Xcode that the CocoaLumberjackSwift frameworks
needs CocoalumberJack to be linked as well.

fix initial build of CocoaLumberjackSwift-iOS

---

Classes/Extensions/DDContextFilterLogFormatter.m
Classes/Extensions/DDDispatchQueueLogFormatter.m

Replace `OSSpinLock` with `pthread_mutex`. Related issue: #886.

Replace OSSpinLock with pthread_mutex

---

Classes/DDFileLogger.m

Given the following two bundle identifiers:
- com.mycompany.app.abcservice
- com.mycompany.app.abcservice2
The latter would reuse/overwrite the log files of the former because `hasPrefix:` would return `YES`.
This fixes the problem by also checking for a space after the app name / bundle identifier.

Fix DDLogFileManagerDefault -isLogFile:

---

Classes/DDLog.m

This merge request fixes / refers to the following issues: #689 and #812
By waiting on the semaphore on the logging queue, we ensure that we don't accidentally lock the main thread.

Fix locking the main thread

---

Classes/DDAbstractDatabaseLogger.m
Classes/DDFileLogger.m
Classes/DDLog.m
Classes/DDTTYLogger.m
Classes/Extensions/DDMultiFormatter.m

This merge request fixes `pod lib lint` warnings. As a result, this fixes also travis-ci failure.
[Details]
`pod lib lint` of CocoaPods 1.4.0 or later enables `-Wimplicit-retain-self` and this merge request fixes this warnings.
In addition, this warning setting seems to be set by default in next version Xcode(9.3)😄

Fixes pod lib lint warnings

---

Classes/DDLog.m

This merge request fixes / refers to the following issues: #906 
Convince the Fortify security analysis tool: avoid double free error by assigning `NULL` to freed pointer.

Convince fortify with assigning NULL to freed ptr

---

Classes/DDLog.h

This merge request fixes the following issues: #920 .
I confirmed that I was able to linked with `THIS_FILE` macro in both Objective-C++ file(.mm) and Objective-C file(.m).

extern "C" for Objective-C++

---

Framework/Lumberjack.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

Adds IDEWorkspaceChecks.plist that is created by Xcode 9.3.
According to [Xcode 9.3 Release Notes](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html), developers should commit this file after Xcode 9.3.
> Xcode 9.3 adds a new IDEWorkspaceChecks.plist file to a workspace's shared data, to store the state of necessary workspace checks. Committing this file to source control will prevent unnecessary rerunning of those checks for each user opening the workspace. (37293167)

Adds IDEWorkspaceChecks.plist 

---

Classes/Extensions/DDDispatchQueueLogFormatter.m

```objective-c
// If you manually create a thread, it's dispatch_queue will have one of the thread names below.
// Since all such threads have the same name, we'd prefer to use the threadName or the machThreadID.
```
I craeted a Thread (on iOS 11.3), and found that it holds a dispatch queue label which is not in the name list. So I added it to the list.

Add new queue label which will be hold by a manual created thread.

---

Classes/DDASLLogCapture.m
Classes/DDASLLogger.m
Classes/DDAbstractDatabaseLogger.m
Classes/DDFileLogger.m

This merge request fixes compiler errors in Xcode when additional pragma checks are enabled:
```
DDASLLogger.m:93:20: Implicit conversion changes signedness: 'int' to 'size_t' (aka 'unsigned long')
DDASLLogCapture.m:132:27: Implicit conversion changes signedness: 'int' to 'unsigned long'
DDASLLogCapture.m:149:69: Implicit conversion changes signedness: 'int' to 'DDLogFlag' (aka 'enum DDLogFlag')
DDASLLogCapture.m:174:48: Implicit conversion changes signedness: '__darwin_time_t' (aka 'long') to 'unsigned long long'
DDASLLogCapture.m:215:34: Implicit conversion changes signedness: 'long long' to 'unsigned long long'
DDFileLogger.m:765:65: Implicit conversion changes signedness: 'uint64_t' (aka 'unsigned long long') to 'int64_t' (aka 'long long')
DDFileLogger.m:955:21: Implicit conversion …
```

Fixed compiler warnings

---

Classes/DDAssert.swift
CocoaLumberjack.podspec
Lumberjack.xcodeproj/project.pbxproj

This PR contains the implementation for #918: two new Swift functions, `DDAssert` and `DDAssertionFailure`. They mimic the stdlib's [`assert`](https://developer.apple.com/documentation/swift/1541112-assert) and [`assertionFailure`](https://developer.apple.com/documentation/swift/1539616-assertionfailure), but they also log a message (using `DDLogError`) if the assertions fails. (The consequence is that, unlike `assert`, the assertion condition for `DDAssert` is always evaluated, even when assertions are disabled.)
cc @bpoplauschi @diederich 
* I chose to create a new file, `DDAssert.swift`, for these function. If you prefer, we could also include them in `CocoaLumberjack.swift`, of course. I found it clearer to separate the …

DDAssert for Swift

---

Classes/DDAbstractDatabaseLogger.m
Classes/DDFileLogger.m
Classes/Extensions/DDContextFilterLogFormatter.h
Classes/Extensions/DDContextFilterLogFormatter.m

Change from NSUInteger to NSInteger in context filter formatter, since the majority of the library uses NSInteger _context.
Mark unused variables as such.
Remove unneeded casts.

Fix common warnings emitted by -Wall -Wconversion -Wextra, etc

---

Classes/DDFileLogger.m

--> Instead, I tested several times manually at local machine.
This merge request fixes / refers to the following issues: #945 
I added synchronous access to `currentLogFileHandle`.

Synchronous access to `currentLogFileHandle`.

---

Classes/CocoaLumberjack.swift
Classes/DDAssert.swift
Classes/SwiftLogLevel.h
CocoaLumberjack.podspec
Framework/Lumberjack/CocoaLumberjackSwift.h
Framework/SwiftTest/AppDelegate.swift
Framework/iOSSwift/AppDelegate.swift
Framework/tvOSSwiftTest/AppDelegate.swift
Framework/watchOSSwiftTest Extension/ExtensionDelegate.swift
Lumberjack.xcodeproj/project.pbxproj

This merge request fixes / refers to the following issues: #774 
As described in #774, the previous `defaultDebugLevel` was a normal global variable, that could change at any time. Therefor the compiler did not strip strings that were logged with an inaccessible level.
This changes this by adding `@inlinable` to the Swift log functions (so the compiler is allowed to inline the code) and using a `static const` definition for the default log level. This definition now cannot be changed in Swift code, but needs to be defined either via the `GCC_PREPROCESSOR_DEFINITIONS` build setting, or using a `#define` in a bridging header of a Swift target.

Use static const for default log level so Swift can strip strings

---

Classes/Extensions/DDDispatchQueueLogFormatter.h
Classes/Extensions/DDDispatchQueueLogFormatter.m
Documentation/CustomFormatters.md

OSAtomicIncrement32 and OSAtomicDecrement32 were deprecated in iOS 10/macOS 10.12/watchOS 3. This doesn't affect anything when targeting earlier releases, but we build lumberjack with newer deployment targets so this silences a couple of warnings.
Similarly asl_log has been deprecated and replaced by os_log. I'm going to look in to conditionally using asl/os based on deployment target as well.

Replace OSAtomic with stdatomic in DDDispatchQueueLogFormatter

---

Classes/DDFileLogger.m
Classes/DDLog.m
Classes/Extensions/DDDispatchQueueLogFormatter.h
Classes/Extensions/DDDispatchQueueLogFormatter.m
Documentation/CustomFormatters.md
Tests/CocoaLumberjack Tests.xcodeproj/project.pbxproj
Tests/Tests/DDAtomicCounterTests.m

This merge request fixes / refers to the following issues: #957 
Improvement to PR #957 Replace `OSAtomic` with `stdatomic` in `DDDispatchQueueLogFormatter`
Created a `DDAtomicCounter` class with `DDAtomicCountable` protocol that encapsulates the atomic counting logic.
Using another macro `DD_OSATOMIC_API_DEPRECATED` instead of all the checks for min os version
Cleaned up the imports of `OSAtomic.h`
Added some basic tests of this new class

Improvement to PR #957 by creating DDAtomicCounter class

---

.swiftlint.yml
.travis.yml
CHANGELOG.md
Classes/CocoaLumberjack.swift
Dangerfile
Framework/Lumberjack.xcworkspace/contents.xcworkspacedata
Gemfile
Gemfile.lock

Added [Danger](https://github.com/danger/danger) integration using their wizard (`bundle exec danger init`):
- Swift lint checks
- warning for PR marked In progress (using PR title)
- warning for big PRs (>500 lines of code)
- warning for source files changed without a change in `CHANGELOG.md`
- check if file additions/deletions from the `Classes` folder are matched by changes to `Lumberjack.xcodeproj`
- warn if the source files were changed but not the tests
- check if Carthage modified and CocoaPods didn't or vice-versa
- check the Xcode settings for new additions - they should be added to the `xcconfig` files
- also check for files added to the xcodeproj that don't match the folder structure (from Finder)
Repaired some Xcode proj paths to the metadata files (not affecting compilation).

Add danger support for PR checks

---

Dangerfile
Demos/OverflowTestMac/main.m

This merge request fixes / refers to the following issues: 
https://github.com/CocoaLumberjack/CocoaLumberjack/pull/965#discussion_r226672415
Danger rule
Fixed one file header: `DemoOverflowTestsMac/main.m`
`Integration/macOSSwiftIntegration/AppDelegate.swift` is removed by another PR, so no need to fix it
Besides those, all the files are passing the check.
Used `sourcefiles_to_check = Dir.glob("*/*/*")` to check locally.

Implemented Danger rule to check each source file header Copyright and format

---

.travis.yml

Travis currently builds all pushes to all branches in the repo. This limits Travis to the master branch. PR builds should not be affected by this. In fact, Travis should only do one build per PR now, instead of also doing a push-triggered build (at least for the PRs coming from branches in this repo).

Let Travis only build for pushes to master branch

---

CocoaLumberjack.podspec

This merge request fixes / refers to the following issues: #976 (See @bpoplauschi 's comment.)
Remove unnecessary `public_header_files` settings in podspec 
because all the headers in `source_files` are public.

Remove unnecessary settings in podspec

---

CHANGELOG.md
Classes/DDFileLogger.m

This merge request fixes / refers to the following issues: On macOS 10.14, log messages are being jumbled when written to disk. The NSFileHandle is not writing to the end of the file correctly resulting in output that overwrites other log messages. I didn't have this problem in 10.13; it appears to be a new issue in 10.14.
Example:
```
2018/11/12 15:16:51:302  Import Prot2018/11/12 152018/11/12 15:16:51:304  Import Serv2018/11/12 15:2018/11/12 15:16:51:306  Import Serv2018/11/12 152018/11/12 15:16:51:307  Import Serv2018/11/12 15:2018/11/12 15:16:51:309  Import Servers Started.
```
This pull requests makes sure to seek to the end of the log file before writing the log message.

Fixes an issue where log messages were being combined or truncated when logged at high speed

---

CHANGELOG.md
Classes/DDFileLogger.m
Classes/DDLog.m

This merge request fixes / refers to the following issues: #995 
The availability checks in DDLog.m in `init` don't work anymore, because `NSAppKitVersionNumber10_0` is no longer a define.
This fixes this by checking for CLI tools with `DD_CLI` (which is used in other places) and `__has_include`.
Furthermore, the memory leak of custom DDLog objects captured in `atexit_b`.
And I've switched to use the constants provided by the frameworks for the notification names.

Fix availability checks in DDLog.m. Also fix memory leak. Fixes #995

---

CHANGELOG.md
Classes/DDFileLogger.h
Classes/DDFileLogger.m
Tests/Tests.xcodeproj/project.pbxproj
Tests/Tests/DDLogFileManagerTests.m

Added property `initialFileContents` to `DDLogFileManagerDefault` to support headers in log files.
Override implementation of `initialFileContents` to insert header text at the beginning of every log file created by the `createNewLogFile:` method.
We wish to include the version and build date of our application at the beginning of the log files generated by CocoaLumberjack. I have not been able to find any obvious way of doing this so I propose adding an `initialFileContents` property to `DDLogFileManagerDefault` which the  `createNewLogFile:` method then uses as an argument for the 'contents' parameter (instead of nil) when calling `createFileAtPath:contents:attributes:`
The intention is to achieve something which is possible …

Added support for log file headers

---

Classes/DDTTYLogger.m

Reduces the size of the codegen for a stripped release archive from
397K to 362K
macOS release build of CocoaLumberjack-Static stripped using strip -x.
...

Reduce size of CocoaLumberjack

---

Dangerfile
Gemfile.lock

This updates Danger itself (by running `bundle update`) and the `Dangerfile`.
In the latter, the copyrights were updated for the new Benchmarking projects.

Update Danger and Dangerfile #trivial

---

.github/stale.yml

As mentioned in #1009, stale bot currently also marks feature requests as stale. This fixes this by adding the Feature Request label to the `exemptLabels` in our stale.yml.

Tell StaleBot to leave Feature Requests alone

---

CHANGELOG.md
Classes/CocoaLumberjack.swift
Documentation/ProblemSolution.md

This merge request fixes / refers to the following issues: #665 
This adds a global variable in Swift (`asyncLoggingEnabled`) which is then used in all log-functions (except `DDLogError`) to define whether logs are written asynchronously or not.

Add global variable to control async logging in Swift

---

Classes/CocoaLumberjack.h

Umbrella headers need to import all public Objective-C header files. Without this, projects may get compiler warnings like: `/<module-includes>:1:1: Umbrella header for module 'CocoaLumberjack' does not include header 'DDLog+LOGV.h'`
This PR adds all public header files to the CocoaLumberjack umbrella header. It also changes the import syntax to use #import <CocoaLumberjack/PublicHeader.h>, which is the proper way to import module-specific files in a public header.
...

Make umbrella header import all public .h files with proper public import syntax

---

Dangerfile

Currently, Danger reports copyrights mistakes in Benchmarking because of a typo in Dangerfile.
Also, Danger reports copyright mistakes in Vendor and FMDB files.
(See #1026 for an example).
This fixes both.

Fix typo in Dangerfile and skip Vendor / FMDB files in Copyright check #trivial

---

Classes/DDFileLogger.m

In #1028, I limited the `rollingFrequency`, but this does not really prevent any overflows (or only by luck). The actual overflow limit is always related to the log file's creation date.
So I've moved the overflow checks to where the values are actually used (in additions and multiplications).
Thanks @hhanesand for pointing out that there's still an issue.
This should now finally fix the overflow issues (#1032).

Prevent overflows in DDFileLogger (again)

---

CHANGELOG.md
Classes/DDFileLogger.m
Tests/Tests/DDFileLoggerTests.m

This merge request fixes / refers to the following issues: #1041 
With the last refactoring for `DDFileLogger` it always used the latest log file, no matter whether it was already archived or not.
This now checks whether the log file info is archived and creates a new one in this case.
Also, a test case was added for log file rolling.

Prevent reuse of already archived log file info

---

CHANGELOG.md
Classes/DDFileLogger.m
Tests/Tests/DDFileLoggerTests.m

This merge request fixes / refers to the following issues: #1048 
When `doNotReuseLogFiles` was set to yes, the `DDFileLogger` would create a new log file on every call to `currentLogFileInfo`. This is fixed now, since we only archive a log file if we're resuming.

Fix creation of too many log files

---

Tests/Tests/DDFileLoggerTests.m

On the iOS simulator, we would have a race condition where test files would be cleaned up before the tested file logger was able to clean up after itself. This fixes this by syncing DDLog's queue and the file logger's queue before deleting the log files/.

Sync internal queues to prevent cleaning up log files too soon in tests

---

CHANGELOG.md
Classes/DDLog.m
Classes/DDTTYLogger.m
Classes/Extensions/DDFileLogger+Buffering.m

This merge request fixes / refers to the following issues: #1050 
This replaces the banned APIs in the list mentioned in #1050 with their safe counterparts.

Replace banned APIs with safe ones

---

CHANGELOG.md
Classes/DDASLLogCapture.m

This merge request fixes / refers to the following issues: #1050 #1056 
Replace one more banned function(sprintf) with safe one(snprint).
According to the [code](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/ios/binary_analysis.py#L142-L145) of #1050, I think `sprintf` should be also replaced.

Replace banned function(sprintf) with safe one(snprint)

---

CHANGELOG.md
Classes/DDAssert.swift

Continuing fixes for #1043
Additional changes to support Swift 5. Backwards compatible.

Additional support for Swift 5 and Xcode 10.2

---

CHANGELOG.md
Classes/DDFileLogger.m

This merge request fixes / refers to the following issues: #1061 
Use `LLONG_MAX` instead of `LONG_LONG_MAX`.
It says in `limit.h` that you should use `LLONG_MAX` instead of `LONG_LONG_MAX`.
/* LONG_LONG_MIN/LONG_LONG_MAX/ULONG_LONG_MAX are a GNU extension.  It's too bad
that we don't have something like #pragma poison that could be used to
deprecate a macro - the code should just use LLONG_MAX and friends.
*/

Use `LLONG_MAX` instead of `LONG_LONG_MAX`

---

Classes/DDAssertMacros.h

Was seeing a BAD_ACCESS crash on one of my log statements because I was passing a string with a %@, and the NSAssert function expects a format string, not a literal.

Fix format string crash.

---

Configs/Module-Shared.xcconfig

Fixes error on macOS build using `Lumberjack.xcodeproj`:
`target 'CocoaLumberjack' has bitcode enabled (ENABLE_BITCODE = YES), but it is not supported for the 'macosx' platform`
Strange thing, that `xcodebuild` doesn't fail

Disable bitcode on macOS builds

---

CHANGELOG.md
Classes/DDFileLogger.h
Classes/DDFileLogger.m

I removed a public variable to provide queue protection in d0fed54ea39d710918f5b9d3627d32a50f889c46 .

Expose current log file info in `didLog` methods.

---

Sources/CocoaLumberjack/DDFileLogger.m

This fixes a regression introduced in d0fed54ea39d710918f5b9d3627d32a50f889c46. The code that checks the previously used NSFileProtectionType key needs to check if the returned key isn't nil, which happens in the simulator (and possibly some other environments where file protection API is not available).
Without this additional check, when the file logger is used in the simulator in an app that can run in the background, the log file is always rotated at launch regardless how large or how old it is (because both key comparisons here return false, so YES is returned from this code block).

fixed an issue with log archiving in the simulator

---

Sources/CocoaLumberjack/DDFileLogger.m

We have an assertion that checks whether the parent folder exists or not. This might fail in simulator builds where we move the log files to archive them, since the parent folder might not exist anymore in this case.
This fixes that problem by limiting the assertion to non-simulator builds.

Limit assertion to non-simulator build

---

.travis.yml
Configs/Module-Shared.xcconfig

This came up while using CocoaLumberjack as a framework dependency. Without `SUPPORTS_MACCATALYST` it didn't build for catalyst for me.
Adding this, allowed Xcode to use the targets as dependencies in a macCatalyst app.

allow building for macCatalyst

---

CHANGELOG.md
Sources/CocoaLumberjack/DDFileLogger.m

This merge request fixes / refers to the following issues: #1106 
This fixes the fact that the rolling timer might fire early (due to its leeway) and then reschedule itself until the leeway has passed.

Correctly include leeway of rolling timer in age comparison

---

CHANGELOG.md
Sources/CocoaLumberjack/DDFileLogger.m
Sources/CocoaLumberjack/include/DDFileLogger.h
Tests/CocoaLumberjackTests/DDLogFileManagerTests.m

* [] I have added the required tests to prove the fix/feature I am adding
This merge request fixes / refers to the following issues: #1103 
As outlined in #1103, we might return nil from `-[DDLogFileManagerDefault createNewLogFile]` if critical errors occurred a few times in a row. 
I've changed the API now to allow propagating the errors (since `DDLogFileManager` is a protocol) and deal with them in `DDFileLogger`. Still, the nullability annotation of `currentLogFileInfo` had to change to `nullable` since we have to return null there, if the creation of a log file fails.

Deal with errors during log file creation

---

CHANGELOG.md
Sources/CocoaLumberjack/DDFileLogger+Internal.h
Sources/CocoaLumberjack/DDFileLogger.m
Sources/CocoaLumberjack/Extensions/DDFileLogger+Buffering.m

This PR fixes duplicated code of -lt_dataForMessage: method. I also changed the signature of -lt_dataForMessage: method which now returns a nullable NSData: it is faster than allocating and returning an empty NSData and data.length still returns zero if data is null.
Finally I prefer to use the modern -enumerateByteRangesUsingBlock: method for accessing NSData buffer. Indeed, it is better to use this rather than bytes property or -getBytes:length: method because they need NSData to map continuous buffer if it contains multiple buffers scattered in memory.

Duplicated log message code

---

Sources/CocoaLumberjack/Supporting Files/DDLegacyMacros.h
Sources/CocoaLumberjack/include/DDLogMacros.h

This PR addresses an annoyance when using oclint/sonar. Because the condition happens in a macro it's considered part of the code base using it and not part of the module, hence it cannot be excluded unless disabling the whole rule or disabling it per usage, which it's super cumbersome.
The infringing rule is "bitwise operator in conditional" basically it's trying to prevent misuses of "&&" the same as "==" vs "=" in conditionals.
...

linting issue spotted by oclint/sonar

---

Sources/CocoaLumberjack/DDAbstractDatabaseLogger.m
Sources/CocoaLumberjack/DDFileLogger.m
Sources/CocoaLumberjack/include/DDAbstractDatabaseLogger.h
Tests/CocoaLumberjackTests/DDBasicLoggingTests.m

This a simple PR that use dispatch_activate() instead of dispatch_resume() since it is the preferred method as stated in the doc:
```
* For backward compatibility reasons, dispatch_resume() on an inactive and not
* otherwise suspended dispatch source object has the same effect as calling
* dispatch_activate(). For new code, using dispatch_activate() is preferred.
```

Use dispatch_activate() instead of disptach_resume() wherever possible.

---

Gemfile.lock

This merge request fixes / refers to the following issues:
```
1 rake vulnerability found in Gemfile.lock on Feb 29
Remediation
Upgrade rake to version 12.3.3 or later. For example:
gem "rake", ">= 12.3.3"
Always verify the validity and compatibility of suggestions with your codebase.
CVE-2020-8130
moderate severity
Vulnerable versions: <= 12.3.2
Patched version: 12.3.3
There is an OS command injection vulnerability in Ruby Rake before 12.3.3 in Rake::FileList when supplying a filename that begins with the pipe character |.
```
Fix the vulnerability reported by Github and also update our gemfile stack - did not yet update to bundler 2.

Updated gemfile dependencies (used bundler 1.17.1)

---

.github/workflows/validations.yml
Dangerfile.swift

This is a small fix on top of #1140 that simplifies the check for command-comments and with that prevents build failures if no command was found.

Simplify checking for command-comment & prevent build failures

---

CHANGELOG.md
Sources/CocoaLumberjack/DDFileLogger.m

This merge request fixes / refers to the following issues: Fixes #1147 
The default log formatter of DDFileLogger localizes the timestamps which isn't helpful for logs.

Do not localize timestamps in default file log formatter

---

CHANGELOG.md
CocoaLumberjack.podspec
Configs/Module-Shared.xcconfig
Package.swift
README.md
Sources/CocoaLumberjack/DDLog.m
Sources/CocoaLumberjack/Extensions/DDDispatchQueueLogFormatter.m

This merge request fixes / refers to the following issues: none
As per discussion in https://github.com/CocoaLumberjack/CocoaLumberjack/pull/1148 with @ffried - soon iOS 8 won't be available in Xcode (in Xcode 12).
This PR prepares CocoaLumberJack for upcoming release of iOS and Xcode and simply just drops iOS 9.
Following PRs in future will also update SPM and project itself to Swift 5.3.
- Drop iOS 8 in order to prepare for September and iOS 14 with Xcode 12 and his minimum deployment target as iOS 8
- Remove availability macros that are not necessary as CocoaLumberJack supports macOS 10.10 and iOS 9.0 and higher
This fixed warnings for Xcode 12 without updating the codebase and Swift version itself and without affecting master and stable Xcode itself - which sounds like a good step to …

Drop iOS 8, remove unnecessary code

---

CHANGELOG.md
Package@swift-5.2.swift

This merge request fixes / refers to the following issues: 
- None
iOS version 8.0 is no longer supported as the minimum deployment version with Swift 5.3 and Xcode 12. Adding CocoaLumberjack to a project as a dependency via SPM will produce this warning in Xcode 12:
```
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.
```

SPM: Bump tools-version to 5.3 (keeping 5.2 support)

---

.github/workflows/validations.yml

I'd like to limit the users who can execute `/run_checks` to collaborator and admin (I think it was the expected behavior?). I also simplified the action for checking out the pull requests from the fork. In fact, I have already implemented this method in some projects and they works fine.
Do you prefer this proposal? TBH, I'm not sure we really need this feature(limit the users who can execute `/run_checks`), but we can do it😅 and it gets better, I think.
As a reminder,  this change will work fine after the merge(not at pull request) due to GitHub Action issue_event specification.
Thanks.

[Proposal] Add `/run_checks` permission

---

CHANGELOG.md
CocoaLumberjack.podspec

This merge request fixes / refers to the following issues: #1161 
Specify CocoaPods version to ensure `swift_version` attribute sets SWIFT_VERSOIN even when user does not set SWIFT_VERSION in his/her target project.
Reference: http://blog.cocoapods.org/CocoaPods-1.4.0/

Specify CocoaPods version to ensure `swift_version` attribute works

---

CHANGELOG.md
Dangerfile.swift
Demos/LogFileCompressor/CompressingLogFileManager.m
Documentation/LogFileManagement.md
Sources/CocoaLumberjack/DDFileLogger.m
Sources/CocoaLumberjack/include/CocoaLumberjack/DDFileLogger.h
Sources/CocoaLumberjackSwiftLogBackend/DDLogHandler.swift
Tests/CocoaLumberjackTests/DDSampleFileManager.m

This merge request fixes / refers to the following issues: #1165 
Currently, there are two hooks in DDLogFileManager for managing archived log files (`didRollAndArchiveLogFile:` and `didArchiveLogFile:`). The only difference is the place where they are called.
This simplifies that by turning the two methods into one with an additional bool parameter that provides that distinction.

Simplify log file manager hooks to one hook

---

CHANGELOG.md
Documentation/CustomContext.md
Documentation/CustomLoggers.md
README.md
Sources/CocoaLumberjack/DDLog.m
Sources/CocoaLumberjack/DDTTYLogger.m
Sources/CocoaLumberjack/include/CocoaLumberjack/DDLog.h
Tests/CocoaLumberjackTests/DDLogMessageTests.m
Tests/Tests.xcodeproj/project.pbxproj

Fix for issue #532 
> this is a simple issue where CocoaLumberjack has a property whose name and type conflicts with the name and type used throughout AppKit and UIKit. 
I agree with @akac, and given that DDLogMessage is an internal class, the rename of the property should not cause any conflicts.
While there may be no real convention on how to use tag, the fact remains that CocoaLumberjack is breaking a lot of very common code of the cocoa target-action pattern.
And I strongly think that CocoaLumberjack should acknowledge this pattern usage and just rename the
property. This way it would be easier to integrated into large existing code bases.
Cheers,
Christopher

#532 Fix tag selectors name and type conflict

---

Sources/CocoaLumberjack/DDTTYLogger.m

This merge request fixes / refers to the following issues: #1178 
In #1178 I've moved the stack allocation inside an `if` scope. Unfortunately, ObjC clears the stack allocation when the variable goes out of *scope* (vs. when the function/method returns). Thus I've now changed the allocation to `alloca`.
(Thanks @sushichop, for the quick review! Sorry that the PR wasn't "ready")

Fix BAD_ACCESS when using the stack in TTYLogger #trivial

---

CHANGELOG.md
Sources/CocoaLumberjack/DDFileLogger.m

[https://github.com/CocoaLumberjack/CocoaLumberjack/pull/1042/files#diff-c8a9bcf29dc1c5256c046b115400ea8ac3327f7200552637f62f8a49ae6f4109R1039](https://github.com/CocoaLumberjack/CocoaLumberjack/pull/1042/files#diff-c8a9bcf29dc1c5256c046b115400ea8ac3327f7200552637f62f8a49ae6f4109R1039) 
This refactor had check if the log file is archived. Just return NO to create new log file. So in `lt_shouldLogFileBeArchived` method to check archived is meaningless. 
I guess the refactoring forgot to delete this judgment.
In other words, If the file has been archived, it's need to create new log file. this place should also return `YES` instead of `NO`.

Remove meaningless judgments in `DDFileLogger`

---

CHANGELOG.md
Sources/CocoaLumberjack/DDFileLogger.m
Tests/CocoaLumberjackTests/DDFileLoggerTests.m

This merge request fixes / refers to the following issues: ... #463 
`maximumNumberOfLogFiles` & `logFilesDiskQuota` of `DDLogFileManagerDefault` is not KVO, they are disabled intentionally.
So it's a bug for user to reset `maximumNumberOfLogFiles` & `logFilesDiskQuota`. 
With KVO crash, I think `setter` is more better!

Use setter to replace kvo for filelogger

---

CHANGELOG.md
Sources/CocoaLumberjack/DDFileLogger.m

Some api in `NSFileHandle`  will be **DEPRECATED** , So It's time to update with new api.

Using new API for `NSFileHandle` to show more infos when has error.

---

CHANGELOG.md
Sources/CocoaLumberjack/DDLog.m

The `loggerQueue` is public, once the user call `flushLog` in the `loggerQueue`, deadlock will occur.
...

Add an assertion to avoid potential deadlock issues for `flushLog`

---

README.md

This merge request fixes / refers to the following issues: #1187
Add README section for the Data Collection Practices

Data Collection Practices

---

.swiftlint.yml
CHANGELOG.md
Sources/CocoaLumberjackSwiftLogBackend/DDLogHandler.swift
Tests/CocoaLumberjackSwiftLogBackendTests/DDLogHandlerTests.swift

With CocoaLumberjack and CocoaLumberjackSwift it's possible to control synchronous/asynchronous logging on a per-message basis. Our implementation of a SwiftLog backend currently couldn't do this.
With this PR it's possible to do this using a metadata-value on the message. The key for this metadata-value is configurable, but has a default of `"log-synchronous"`. Said default is accessible via `DDLogHandler.defaultSynchronousLoggingMetadataKey`.

Add per-message synchronous logging control for DDLogHandler

---

Lumberjack.xcodeproj/project.pbxproj
Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack-Static.xcscheme
Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjack.xcscheme
Lumberjack.xcodeproj/xcshareddata/xcschemes/CocoaLumberjackSwift.xcscheme
Sources/CocoaLumberjack/CLI/CLIColor.m
Sources/CocoaLumberjack/DDASLLogCapture.m
Sources/CocoaLumberjack/DDASLLogger.m
Sources/CocoaLumberjack/include/CocoaLumberjack/CLIColor.h

* There's one failing test, but it's red on `master`/Xcode 12.4 as well...?
This merge request fixes / refers to the following issues: #1208 
As discussed in #1208, this PR adds the 
```objc
#import <TargetConditionals.h>
```
statements required for Xcode 12.5 Beta 1 to compile the SPM package.
Since this is an early beta and the [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-beta-release-notes/) don't mention any change here, there's a possibility that the original problem of #1208 will disappear by itself, so please don't merge this PR yet.

WIP: Add TargetConditionals Import (Xcode 12.5)

---

CHANGELOG.md
Sources/CocoaLumberjack/include/CocoaLumberjack/DDAssertMacros.h

* [-] I have added the required tests to prove the fix/feature I am adding
* [-] I have updated the documentation (if necessary)
```
Test Suite 'All tests' passed at 2021-04-01 16:53:54.808.
Executed 62 tests, with 0 failures (0 unexpected) in 4.352 (4.356) seconds
```
```
Moorea:CocoaLumberjack levi$ pod lib lint
-> CocoaLumberjack (3.7.0)
- NOTE  | [CocoaLumberjack/Core,CocoaLumberjack/Swift] xcodebuild:  note: Using new build system
- NOTE  | [CocoaLumberjack/Core,CocoaLumberjack/Swift] xcodebuild:  note: Building targets in parallel
- NOTE  | [CocoaLumberjack/Core,CocoaLumberjack/Swift] xcodebuild:  note: Using codesigning identity override: -
- NOTE  | [CocoaLumberjack/Core,CocoaLumberjack/Swift] xcodebuild:  note: Planning build
- NOTE  | [CocoaLumberjack/Core,CocoaLumberjack/Swift] …
```

Adding `DDAssertionFailure` macro

---

CHANGELOG.md
CocoaLumberjack.podspec
Configs/Module-Shared.xcconfig

This prepares the release 3.7.1.
~Currently depends on #1216 (and contains the same changes, thus not worth a review until #1216 is merged)~

Prepare Release 3.7.1

---

CHANGELOG.md
CocoaLumberjack.podspec
Configs/Module-Shared.xcconfig
Sources/CocoaLumberjack/DDLog.m
Sources/CocoaLumberjack/include/CocoaLumberjack/DDLog.h

This merge request fixes / refers to the following issues: #1177 #1223 
In #1177 the `tag` property was deprecated and superseded by `representedObject`. However, the underlying `_tag` field was removed completely instead of simply deprecated. This caused the change to become a breaking change.
This re-introduces the underlying `_tag` field and also marks it as deprecated.

Re-introduce _tag field and deprecate it

---

CHANGELOG.md
Sources/CocoaLumberjack/DDFileLogger.m

DDFileLogger will fail to get the offset of the log file when `_currentLogFileHandle` isn't initialized, and the log error message "DDFileLogger: Failed to get offset: (null)" will appear.
This happens when the `maximumFileSize` of a DDFileLogger instance is set immediately after the instance is created, for example:
```objc
fileLogger = [[DDFileLogger alloc] init];
fileLogger.maximumFileSize = 1024 * 1;  //  1 KB
fileLogger.rollingFrequency = 60;       // 60 Seconds
```
The code is copied from `Demos/RollingTestMac`, and I believe this is a common usage. The issue can also be reproduced in the demo.

Fix "DDFileLogger: Failed to get offset" when setting maximumFileSize

---

Sources/CocoaLumberjack/DDFileLogger.m

There is a problem when we call new `NSFileHandle` APIs that return errors: if the `_currentLogFileHandle` is `nil`, it will return both `FALSE` for result and `nil` for the error. This will generate false error reports with `NSLogError()`.
There is two ways for fixing this:
1. Check both result set to `FALSE` and error being not `nil` before calling `NSLogError()`.
2. Don't call the API if `_currentLogFileHandle` is `nil` at first place!
I preferred the second solution because it will save CPU cycles.
I did also not include PR #1234 on purpose because I think my solution is better. Let me explain:
1. The way it is fixed in PR #1234, breaks the comment just above that says "Keep it FAST"!
2. If `_currentLogFileHandle` is `nil` when `-lt_maybeRollLogFileDueToSize` is called, it is either …

Fixed false positive error reports.

---

README.md

Just update the raw link to relative link to display markdown document.

Fix markdown link to relative path #trivial

---

Sources/CocoaLumberjack/DDOSLogger.m

This merge request fixes / refers to the following issues: #1243
Since `sharedInstance` is a  class property, it seems that we need to add the annotation to `DDOSLogger.m` , not `DDOSLogger.h`.

Follow-up to add annotations to `DDOSLogger`

---

Sources/CocoaLumberjack/include/CocoaLumberjack/DDDispatchQueueLogFormatter.h

method is already declared in protocol with nullable result type
Fixes nullability conflict in DDDispatchQueueLogFormatter.h #1250

Fixed nullability conflict in DDDispatchQueueLogFormatter.h #1250

---

Sources/CocoaLumberjack/DDFileLogger.m

This merge request fixes / refers to the following issues: on Catalyst apps log files are inaccessible for the app to read/write.
On Catalyst apps setting NSFileProtectionKey attribute to NSFileProtectionCompleteUnlessOpen for log files leads to `Can't open file` error. To prevent this I excluded the corresponding code from compiling on Catalyst environment.

Fix file access issue in Catalyst apps

---

CHANGELOG.md
Sources/CocoaLumberjack/DDTTYLogger.m

This merge request fixes / refers to the following issues: Fixes #1267
For CLI apps, the TTY logger is still useful.

Only show warning for DDTTYLogger if it's not a CLI app

---

Sources/CocoaLumberjack/DDFileLogger.m

[_currentLogFileHandle synchronizeAndReturnError:&error] can return NO without error.
DDFileLogger will put "DDFileLogger: Failed to synchronize file: nil" to console.
This patch prevents the problem.
...

Fix for "DDFileLogger: Failed to synchronize file: nil"

---

Sources/CocoaLumberjack/DDFileLogger.m

Please revert PR #1274 because it was not very well discussed. Can we reproduce that "DDFileLogger: Failed to synchronize file: nil" log? Is it occurring in the "@available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)" branch of the code?
I prefer to have a log with nil error showing that something went wrong rather than silently ignoring the failed status returned by -synchronizeAndReturnError: method.
Moreover the PR broke -lt_maybeRollLogFileDueToSize: method if the returned status of -getOffset:error: method is false but error is nil: fileSize will be undefined in that case.
Lastly, I have fixed -createNewLogFileWithError: method since error parameter is nullable.
Regards

Revert pr 1274

---

Sources/CocoaLumberjack/DDLog.m
Sources/CocoaLumberjack/include/CocoaLumberjack/DDLog.h
Tests/CocoaLumberjackTests/DDLogMessageTests.m

This PR will fix -isEqual: and -hash methods for DDLogMessage class:
1. `[super isEqual:other]` always returns `FALSE` since `[NSObject isEqual:]` compares pointers only.
2. `[otherMsg->_function isEqualToString:_function]` always returns `FALSE` if `otherMsg->_function` is `nil`. Added a test for that.
3. Removed the test for `_fileName` since it is a derivative of `_file`.
4. Removed the test for `_options` since it is not relevant for messages comparison.

Fixed -isEqual: and -hash methods for DDLogMessage class.

---

Configs/Module-Shared.xcconfig
Sources/CocoaLumberjack/DDLog.m
Tests/CocoaLumberjackTests/DDFileLoggerTests.m
Tests/CocoaLumberjackTests/DDLogFileManagerTests.m

In PR #1280, `@(file)` could now return nil value. I fixed the nullability conflict by setting file parameter to empty string in that case. Maybe we could use another constant string for that like `@"unknown"`?

Fixed nullability conflict or file parameter for DDLogMessage creation.

---

Configs/Module-Debug.xcconfig
Sources/CocoaLumberjack/DDFileLogger.m

After enabling nullability violations checks, I found an issue where `_currentLogFileInfo` could be used before being initialized. This PR fixes that.

Fix nullability violations

---

Configs/Tests-Debug.xcconfig
Configs/Tests-Release.xcconfig
Configs/Tests-Shared.xcconfig
Tests/Tests.xcodeproj/project.pbxproj
Tests/Tests.xcodeproj/xcshareddata/xcschemes/OS X Tests.xcscheme
Tests/Tests.xcodeproj/xcshareddata/xcschemes/Swift Tests.xcscheme
Tests/Tests.xcodeproj/xcshareddata/xcschemes/iOS Tests.xcscheme

This PR fixes warnings for Xcode 13.2.

Bump Tests project to Xcode 13.2.

---

Sources/CocoaLumberjack/DDFileLogger.m

<br/>
This merge request fixes / refers to the following issues: Maybe (hopefully?) #1276 
We were using `dispatch_time` for scheduling the log file rolling timer. However, `dispatch_time` pauses when the machine goes to sleep. Thus the log file rolling interval might be "strange" as in not being exactly the time that was specified as rolling interval on the logger.
This PR now makes the switch to `dispatch_walltime` which should yield better results.
[The documentation](https://developer.apple.com/library/archive/documentation/General/Conceptual/ConcurrencyProgrammingGuide/GCDWorkQueues/GCDWorkQueues.html) even explicitly recommends using `dispatch_walltime` for larger intervals:

Use dispatch_walltime for scheduling log file rolling timer

---

Sources/CocoaLumberjack/DDFileLogger.m
Sources/CocoaLumberjack/include/CocoaLumberjack/DDFileLogger.h
Tests/CocoaLumberjackTests/DDFileLoggerTests.m
Tests/CocoaLumberjackTests/DDSampleFileManager.h
Tests/CocoaLumberjackTests/DDSampleFileManager.m

<br/>
When the logger is trying to reuse an older log file, if the log file is a symlink the logger will write into the link file. This can result in different issues, specially if the log file names are custom. 
To prevent this, first check if the file is symlink, and when it is recreate it as regular file.

Don't log into symlink files

---

Configs/Module-Shared.xcconfig
Sources/CocoaLumberjack/DDFileLogger.m
Sources/CocoaLumberjack/DDTTYLogger.m
Sources/CocoaLumberjack/include/CocoaLumberjack/DDLog.h
Sources/CocoaLumberjack/include/CocoaLumberjack/DDTTYLogger.h
Tests/CocoaLumberjackTests/DDBasicLoggingTests.m

<br/>
This PR fixes a couple of build warnings, some of which show up whenever I build a project which uses CocoaLumberjack as an SPM package dependency:
- An implicit nullable to non-nullable conversion that is shown whenever CocoaLumberjack is built in Xcode.
- Warnings about promoting floats to doubles (when using float literals with CGFloat, which is a double on 64b platforms). These warnings show up when `-Wdouble-promotion` is on, even if the warning is just configured for client code that includes the CocoaLumberjack headers.
- A warning about an extra semicolon. This warning shows up when `-Wextra-semi` is on, even if the warning is just configured for client code that includes the CocoaLumberjack headers.
The full details can be found in the individual commit messages.
Let me …

Fix code-level build warnings

---

Sources/CocoaLumberjack/DDTTYLogger.m
Sources/CocoaLumberjack/include/CocoaLumberjack/DDTTYLogger.h

<br/>
https://github.com/CocoaLumberjack/CocoaLumberjack/pull/1317 fixed double conversion warnings and also enabled `-Wdouble-promotion`. This created warnings when building for 32-bit watchOS, so I added explicit casts to silence the warnings.

Silence double conversion warnings for 32-bit watchOS

---

Configs/Module-Shared.xcconfig

<br/>
This allows the framework to build for multiple platforms which fixes errors building when a project uses CocoaLumberjack in both iOS and watchOS targets.
Without this set we get errors when building with CocoaLumberjack added as a dependency directly through Xcode (rather than using pods, Carthage, or SPM).

Enable ALLOW_TARGET_PLATFORM_SPECIALIZATION

---

CHANGELOG.md
Package.resolved
Package.swift
Package@swift-5.5.swift
Package@swift-5.6.swift
Sources/CocoaLumberjackSwiftLogBackend/DDLogHandler.swift
Tests/CocoaLumberjackSwiftLogBackendTests/DDLogHandlerTests.swift

<br/>
Swift-log recently added so-called `MetadataProvider`s. This updates the minimum swift-log version to 1.5.0 and implements the necessary changes to support those new providers.

Update to swift-log 1.5.2, implement metadata providers

---

Sources/CocoaLumberjack/DDTTYLogger.m

<br/>
1. Changed `int` to `size_t` for `iovec_len` to avoid negative values and improve type safety.
2. Added `max_iovec_len` constant to ensure that the maximum size of the `v` array is known and to prevent buffer overflows.
3. Initialized `v` to zero to avoid potential use of uninitialized memory.
4. Removed unnecessary else branch for setting empty `iov_base` and `iov_len` for `v[0]`, `v[1]`, and `v[max_iovec_len - 1]`.
5. Added check to ensure that the length of the `msg` buffer does not exceed the maximum length allowed for the `iov_base` field in the `struct iovec` array.
6. Added check to ensure that `_automaticallyAppendNewlineForCustomFormatters` is true and that the last character of the `msg` buffer is not already a …

Fix for possible buffer overflow

---

.github/workflows/validations.yml

<br/>
Now we can remove workaround for `pod lib lint` on watchOS simulator.
The original issue was fixed by CocoaPods 1.12.0
See https://github.com/CocoaPods/CocoaPods/pull/11660. 
And `macos-latest` image includes this CocoaPods version.

Remove workaround for `pod lib lint`

---

Sources/CocoaLumberjack/DDFileLogger.m
Sources/CocoaLumberjack/Extensions/DDFileLogger+Buffering.m

* Addresses a build warning in Xcode 14.3
<br/>
This merge request fixes / refers to the following issues: #1338 
Add "void" to function declarations that take no arguments (seems to be a new standard with Xcode 14.3)

Adding missing 'void' in function declarations

---

CHANGELOG.md
Sources/CocoaLumberjack/DDLog.m
Sources/CocoaLumberjack/include/CocoaLumberjack/DDLog.h
Sources/CocoaLumberjackSwift/CocoaLumberjack.swift
Sources/CocoaLumberjackSwift/DDAssert.swift
Sources/CocoaLumberjackSwiftLogBackend/DDLogHandler.swift
Tests/CocoaLumberjackSwiftTests/DDLogCombineTests.swift
Tests/CocoaLumberjackSwiftTests/DDLogMessageFormatTests.swift
Tests/CocoaLumberjackTests/DDContextFilterLogFormatter+DeprecatedTests.m
Tests/CocoaLumberjackTests/DDContextFilterLogFormatterTests.m
Tests/CocoaLumberjackTests/DDLogMessageTests.m
Tests/Tests.xcodeproj/project.pbxproj

<br/>
This merge request fixes / refers to the following issues: fixes #1346 
This adds a new `messageFormat` property to `DDLogMessage`. While more or less trivial to implement in Objective-C, in Swift a new `DDLogMessageFormat` type was introduced, that composes the C-Format from an interpolation.
It should result in the same messages as before - just with the format being generated as well.
Since it's impossible to generate an `NSArray` from a `va_list`'s elements (without knowing the types inside the `va_list`), we currently cannot persist the format arguments in `DDLogMessage`. The Swift version would actually be able to do this (due to collecting the args as well).
However, due to possible side effects (objects living longer than they should, not being thread-safe), I've opted to …

Preserve message format in DDLogMessage

---

Sources/CocoaLumberjack/DDFileLogger.m
Sources/CocoaLumberjack/DDLog.m
Sources/CocoaLumberjack/Extensions/DDDispatchQueueLogFormatter.m
Sources/CocoaLumberjack/include/CocoaLumberjack/DDAssertMacros.h

<br/>
[Apple's String Format docs](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Strings/Articles/formatSpecifiers.html#//apple_ref/doc/uid/TP40004265-SW1) recommend avoiding `%s` whenever possible:
I've also seen it cause issues when the underlying C-String has strange memory management. Using `@()` instead should solve that.

Replace %s with modern Objective-C string creation

---

Sources/CocoaLumberjack/DDFileLogger.m

<br/>
This merge request fixes / refers to the following issues: #1358

Fix app background-mode not correctly detected in app extensions

---

Sources/CocoaLumberjack/DDFileLogger.m

@ffried Since you opted for removing the lt_currentLogFileHandle, here is my PR to fix #1357
<br/>
This merge request fixes / refers to the following issues: #1357
...

Fix DDFileLogger rollingFrequency and maximumFileSize not being honored

---

Documentation/DynamicLogLevels.md
Documentation/GettingStarted.md
Documentation/PerUserLogLevels.md

<br/>
Fixes https://github.com/CocoaLumberjack/CocoaLumberjack/issues/1382.

Update doc from DDLogLevelWarn to DDLogLevelWarning to match library

---

Sources/CocoaLumberjack/DDFileLogger.m
Sources/CocoaLumberjack/include/CocoaLumberjack/DDFileLogger.h
Tests/CocoaLumberjackTests/DDFileLoggerTests.m

<br/>
This merge request fixes / refers to the following issues: #1371  
This adds a new `logMessageSerializer` property to the `DDLogFileManager` protocol. The serializer is of a new protocol `DDFileLogMessageSerializer` type that defines only one method `-dataForMessage:`. This type can be used to change the binary representation of messages in log files.
By default, the `DDFileLogPlainTextMessageSerializer` is used, that serializes messages in UTF-8 plain text (just as the file logger did internally up until today).

Allow different binary formats for DDFileLogger

---

CHANGELOG.md
Sources/CocoaLumberjack/DDOSLogger.m
Sources/CocoaLumberjack/include/CocoaLumberjack/DDOSLogger.h
Sources/CocoaLumberjackSwiftLogBackend/DDLogHandler.swift
Tests/CocoaLumberjackSwiftLogBackendTests/DDLogHandlerTests.swift
Tests/CocoaLumberjackTests/DDOSLoggingTests.m

<br/>
This merge request fixes / refers to the following issues: #1409 
This improves the DDOSLogger implementation with points that were brought up in #1409.
- Cleanup properties and methods.
- Raise `DDLogFlagWarn` messages to the `.error` level in OSLog (which is what Apple does).
- Add `DDOSLogLevelMapper` to allow custom mapping from `DDLogFlag` -> `os_log_type_t`.

Improve DDOSLogger

---

Sources/CocoaLumberjack/DDOSLogger.m
Sources/CocoaLumberjack/include/CocoaLumberjack/DDOSLogger.h

<br/>
This merge request fixes / refers to the following issues: -
With #1410, the designated initializer of DDOSLogger _should_ have been changed, but couldn't since it would be a breaking change. After the version now being bumped to 3.9.0, this PR updates the designated initializer of DDOSLogger.

Change designated initializer on DDOSLogger

---

Sources/CocoaLumberjack/DDFileLogger.m
Sources/CocoaLumberjack/include/CocoaLumberjack/DDFileLogger.h

<br/>
This merge request fixes / refers to the following issues: Fixes #1424 
File locking was introduced in #1367 but seems to be problematic when apps are e.g. suspended in the background. The system then checks for any file locks that are still held and if any, kills the process.
There are workarounds (like starting a background job that flushes the logs), but given that these are _always_ necessary, even though file locking is only necessary when logging to the same file from multiple processes (which is **not** the default), it makes sense to turn _off_ file locking by default, but allow users that customize the file name / path to also enable file locking.

Make file locking optional

---

Sources/CocoaLumberjack/DDFileLogger.m
Sources/CocoaLumberjack/include/CocoaLumberjack/DDFileLogger.h
Tests/CocoaLumberjackTests/DDFileLoggerTests.m

<br/>
This merge request fixes / refers to the following issues: Resolves #1434
Add (optional) `fileManager` to `DDLogFileManager` protocol and a corresponding implementation to `DDLogFileManagerDefault` for convenience.
`DDLogFileInfo` also uses a file manager internally, which is why it also needs to store a file manager now.

Allow custom NSFileManager's on DDLogFileManager's
